// #157: real NCERT Q1 TEST-only product, interaction and academic non-grant audit.
// Runs on already generated bytes, not hand-authored HTML or canonical pages.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
let playwright;
try { playwright = require('playwright'); }
catch { playwright = require(path.join(execFileSync('npm', ['root', '-g']).toString().trim(), 'playwright')); }

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'public');
const product = path.join(root, 'test/products/ncert-u01-q01');
const receipt = JSON.parse(fs.readFileSync(path.join(product, 'deploy-receipt.json'), 'utf8'));
assert.equal(receipt.draft, true);
assert.equal(receipt.accepted, false);
assert.deepEqual(receipt.roles, ['CORE2', 'CORE1A']);
assert.equal(receipt.selection_counts.core2, 1);
assert.deepEqual(receipt.gaps, []);
assert.equal(receipt.pdf.status, 'PRINTED');
for (const name of ['core1a.pdf', 'core2.pdf']) {
  assert.equal(fs.readFileSync(path.join(product, name)).subarray(0, 5).toString(), '%PDF-');
  assert.deepEqual(
    fs.readFileSync(path.join(product, name)),
    fs.readFileSync(path.join(root, '..', 'docs/test/products/ncert-u01-q01', name)),
  );
}

const types = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.pdf':'application/pdf'};
const server = http.createServer((req,res)=>{
  let url;
  try { url = new URL(req.url, 'http://localhost'); } catch { res.writeHead(400).end();return; }
  const filename = path.resolve(root, '.'+decodeURIComponent(url.pathname));
  if (!filename.startsWith(root+path.sep) || !fs.existsSync(filename) || !fs.statSync(filename).isFile()){
    res.writeHead(404).end();return;
  }
  res.writeHead(200, {'content-type': types[path.extname(filename)] || 'application/octet-stream'});
  fs.createReadStream(filename).pipe(res);
});
await new Promise(resolve=>server.listen(0, '127.0.0.1', resolve));
const origin='http://127.0.0.1:'+server.address().port;
const browser=await playwright.chromium.launch({headless:true});
try {
  for (const width of [390,768,1280]) {
    const context=await browser.newContext({viewport:{width,height:860}});
    const page=await context.newPage();
    const questionId='ncert-exemplar-g9-math-u01-q01';
    await page.goto(origin+'/test/products/ncert-u01-q01/core2.html');
    const article=page.locator('article[data-g9-role="CORE2"][data-g9-unit="'+questionId+'"]');
    assert.equal(await article.count(),1,'original source ID must own exactly one Core2 unit');
    assert.match(await article.locator('[data-g9-block=source_identity]').innerText(),
      /Verified curricular source, faithful NCERT wording/);
    assert.match(await article.locator('[data-g9-meta-kind=provenance]').innerText(),
      /NCERT source custody witnessed/);
    assert.equal(await article.locator('input[data-g9-choice]').count(),4);
    const solution=article.locator('details[data-g9-payload-ref$="-solution"]');
    assert.equal(await solution.count(),1);
    assert.equal(await article.locator('[data-g9-solution-move]').count(),0,
      'answer steps must not materialise before a committed attempt');
    await solution.locator('summary').click();
    assert.equal(await solution.evaluate(el=>el.open),false,
      'attempt-gated solution must not open on an uncommitted question');
    await article.locator('input[data-g9-choice][value="2"]').check();
    await article.locator('[data-g9-commit]').click();
    assert.equal(await article.getAttribute('data-attempted'),'1');
    await solution.locator('summary').click();
    assert.equal(await solution.evaluate(el=>el.open),true);
    assert.ok((await solution.innerText()).includes('real number'),
      'protected authored answer must be available post-attempt');
    const concept=article.locator('a[data-g9-concept-link]');
    assert.equal(await concept.count(),1);
    await concept.click();
    await page.waitForURL('**/core1a.html?**');
    assert.match(await page.locator('article[data-g9-role="CORE1A"]').innerText(),
      /Every rational number is real/);
    const back=page.locator('a[data-g9-return-link][data-g9-practice-link]').first();
    assert.equal(await back.count(),1,'concept route must provide a return to original question');
    await back.click();
    await page.waitForURL('**/core2.html#'+questionId);
    assert.equal(await page.locator('article[data-g9-role="CORE2"] input[data-g9-choice][value="2"]').isChecked(),true,
      'attempt answer should survive concept navigation');
    await context.close();
    console.log('PASS Q1 learner route',width,'px — gated attempt, answer, concept, return and custody');
  }
} finally {
  await browser.close();
  await new Promise(resolve=>server.close(resolve));
}
console.log('PASS: TEST NCERT Q1 technical learner journey only, accepted=false');
