"""Bind manually reasoned coaching verdicts to pinned R4 inputs and render bytes.

This script serializes review, not semantic scoring. The twenty rows below were
written after deriving the tasks and inspecting both A/B copies. It deliberately
records revisions and partial evidence; no counts, author verdicts or lint PASS
are inputs to the academic judgement.
"""
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path
from lxml import html

BASIS = '59cfb081a96b6d15ad9c5a6ded771b2dce00091d'
ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent
FACETS = ['H1','H2','H3','S1','S2','S3','P1','P2','P3','M1','M2','M3']
STATUS = {'A':'ACCEPT_BOUNDED','P':'PARTIAL_COACHING_FINDING','R':'REVISE','W':'ACCEPT_WAIVER'}

DERIVATIONS = {
 'D3': [
  'A fixed unique nitrate double bond predicts unequal positions, contradicting supplied equivalence. Three planar N sigma directions support local sp2; CO2 and NH3 refute equality-implies-sp2.',
  'NO3- valence count 5+3*6+1=24. Three sigma pairs and six in-plane oxygen lone pairs use18; perpendicular p space uses6 across N+threeO=4 functions. Contributors preserve nuclei/charge/count.',
  'Allene terminal C each has3 sigma neighbours; central C has2. Local labels sp2/sp/sp2 conserve four basis functions each; two central orthogonal residual p directions align separately, forcing perpendicular terminal sigma planes in this model.',
  'Ethene has one aligned p pair. Allene central sigma allocation leaves two mutually orthogonal p directions. Geometry follows those alignments; Pauli restricts electronic state occupancy, not participation of an atomic basis function in multiple molecular combinations.',
  'Equivalent bonds occur with2 CO2,3 nitrate,4 NH3 local domains; premise true/consequence false for CO2 or NH3 falsifies universal implication. CH4 supplies fresh four-direction counterexample.',
  'Propyne carbon labels sp3/sp/sp. Four C-H and two C-C connected pairs give6 sigma; triple contributes2 pi. C3H4 valence16=12 sigma electrons+4 pi electrons; ethyne has3 sigma/2pi.',
  'CO3(2-) count4+18+2=24. Three sigma pairs+six in-plane O pairs=18, leaving6 perpendicular electrons in four functions. Contributor-average formal O charge -2/3 is bookkeeping; electron-density partial charge depends on partition scheme.',
  'Axial sigma connectivity can survive relative ethane torsion; relative ethene p alignment changes. This does not hold all donor/acceptor interactions fixed or determine a unique torsional energy decomposition.',
  'Approximately planar butadiene has four adjacent p-bearing carbons; 1,4-pentadiene has a saturated CH2 interruption in the ordinary contiguous p path. That model statement is not a theorem excluding all through-bond/space interactions.',
  'Propyne and allene require atom-local ledgers, four-function conservation and inter-centre orientation checks. Their mixed labels falsify assigning a single molecule-wide hybrid label.'
 ],
 'D4': [
  'Given planar amide donor conditions permit three sp2-like N sigma functions plus a p-like lone-pair donor. Three bonds+lone pair is a Lewis inventory, not an unconditional localized-sp3 instruction; basis decomposition remains a model.',
  'CH3NO valence4+3+5+6=18, total6+3+7+8=24. Donor/carbonyl three-centre pi subspace has lone pair2+carbonyl pi2=4. Rotating N around fixed C-N changes donor orientation, not inventories. A representation must actually show corresponding initial/twisted axes.',
  'Given twist reduces alignment/delocalisation contribution in the supplied model. That trend needs orientation/interaction reasoning, not label-as-cause. Additional Hamiltonian/energy contributions are needed for strength or barrier.',
  'Amide direct N-C(O) adjacency supports donor/acceptor continuity under the given alignment conditions; saturated-spacer site lacks the same ordinary path. Counterfactual remove spacer or add suitable aligned unsaturated bridge requires rechecking, not a proximity-only test.',
  'Four-domain CH4/NH3/H2O introductory labels coexist with different bonded-atom counts4/3/2, nuclear shapes and approximate angles. The observations refute unique angle/shape and do not uniquely invert an orbital basis; amide adds applicability boundary.',
  'The task recalls locality assumptions then judges whether they hold for A/B. Aligned acceptor adjacency and delocalisation evidence defeat automatic identical four-entry local classification. Primary justification/application is not pure recall.',
  'CH3 radical valence4+3=7; three sigma pairs use6 leaving1 in supplied p-like SOMO. CH3+ count6 leaves0 under its local model. Three bonds alone do not determine residual occupancy.',
  'Strictly pyramidal versus approximately planar accounts make different geometric predictions; controlled geometry/bond metrics constrain them. Independent specified spectral/dynamic/electronic evidence can add constraints. Geometry alone yields no unique donation strength, hybrid coefficients or barrier.',
  'cos0=1,cos60=1/2,cos90=0. An unspecified independent energy contribution may vary at fixed overlap. For H=[[epsilon,t],[t,epsilon]], t=t0*cos(theta), determinant gives eigenvalues epsilon +/- |t|. Weak nondegenerate coupling can instead be quadratic; no universal total-energy law follows.',
  'NH3 tests bonded-atom versus domain geometry; allene tests residual orientations; formamide tests donor/acceptor applicability; spacer tests continuity. Keep useful local ledger, add occupancy/path/alignment and evidence boundaries; radical supplies changed occupancy test.'
 ]
}

# Each row contains twelve explicitly authored decisions in FACETS order.
# A/B support text is identical in R4, but metadata/classification differs and is
# separately preserved below. Shared text judgments are not forty independent
# inventions or a human learner outcome study.
NOTES = {
 'D3': [
  'A:Separates supplied equality from selected contributor.|R:Names one delocalised description before requested model choice.|A:Prediction-versus-observation comparison leaves warrant to learner.|A:Three valid charged Lewis contributors orient the supplied species; layout explicitly not measured angles.|P:Repeated contributor drawing and directive do not demonstrate predictive model comparison.|W:Further completed diagram would settle requested model; waiver justified only after useful bridge.|R:Hint2 and answer-specific delocalisation metadata settle or strongly cue requested choice.|A:Exact nitrate repair teaches fixed-bond contradiction and CO2 boundary.|A:Warrants supplied equivalence and independently checks hybrid criterion via counterexample.|A:Permanent selected double-bond interpretation is a plausible contextual error.|P:Repeated predictions can suggest a held model; generic EXPLAIN template error is not identical to localized-bond error.|A:Contradiction plus independent sigma accounting restores bounded rule.',
  'A:Separates contributors and full pi-space ledger.|A:Warns drawn double bond is not full occupancy without supplying count.|A:List-and-preserve operation leaves representation construction.|A:Correct nitrate contributors and formal charge orient translation.|P:No actual sigma/perpendicular correspondence frame or empty electron ledger is shown.|W:Completing original diagram would perform requested representation; neutral bridge still needed.|A:Original diagram/count retained as learner work in authored preattempt support.|A:Exact nitrate repair includes local spaces and contributor invariants.|A:24=18+6 ledger independently checks solution accounting.|A:Switching and omitted terminal pairs are genuine representation errors.|A:Repeated nitrate/carbonate two-electron answers differ from a corrected slip, conditionally.|A:Six-electron four-centre model preserves nuclei/charge; no switching ontology.',
  'A:Local allocation precedes terminal-plane inference.|R:Supplies requested central sp label before learner assignment.|A:Alignment matching still leaves terminal-plane deduction.|A:Allene connectivity is correct and makes no measured-plane claim.|P:No empty local allocation/end-on frame connects sigma and residual directions.|W:Third completed allene projection would be the original answer.|R:Requested hybrid label exposed by hint2.|A:Local orbital repair explains terminal/central allocation and orientation.|A:Whole-model rotation preserves relative perpendicularity; appropriate geometric check.|A:Copied coplanar double-bond picture is a plausible held error.|A:Ethene/allene contrast differentiates repeated single-direction mapping from slip, conditionally.|A:Four-function accounting plus two distinct alignments explains the plane relation.',
  'A:Focuses overlap rather than invalid occupancy warrant.|A:Pauli versus basis-function distinction is a useful general principle.|A:Comparing two overlap directions leaves connected account to learner.|A:Correct ethene/allene connectivity introduces supplied geometries.|P:No two-view direction scaffold links terminal sigma plane to p direction.|W:Completing the two-plane argument would settle target; retain neutral frame.|A:Full directional chain remains learner work.|A:Repair explains geometry and rejects one-AO-one-bond prohibition.|A:Multicentre nitrate is a valid counterexample to alleged orbital-use ban.|A:Pauli misuse is contextual misconception; generic synthesis template only partly matches.|A:Contrast across nitrate/allene tests persistence of faulty warrant, not an actual diagnosis.|A:Repaired rule states introductory construction without universal zero-overlap proof.',
  'A:Highlights criterion under audit.|A:Separates equality and model allocation without assigning species labels.|A:Counterexample search leaves actual refutation.|A:Correct CO2/nitrate/NH3 drawings retain supplied comparison.|P:Directive adds no empty premise/consequence or domain-comparison visual table.|W:Completed counterexample table would reveal conclusion; neutral table is enough.|A:Specific counterexample labels/results remain protected.|A:Repair provides CO2/NH3 warrants and CH4 boundary.|A:True premise/false consequence is correct refutation; changed CH4 strengthens check.|A:Equivalence-implies-sp2 is exact contextual wrong rule.|A:Fresh CH4/CO2 local ledger distinguishes repeated wrong criterion from corrected slip, conditionally.|A:Replacement procedure excludes equality as sufficient criterion.',
  'A:Clarifies local versus global inventories.|A:General triple-bond component rule still leaves whole-molecule accounting.|A:Number-and-count procedure leaves totals and classifications.|A:Propyne drawing has actual H counts and triple connectivity.|P:No separate blank local-domain and whole-bond inventory is visualized.|W:Additional completed count would perform target; two stages adequate if bridge enhanced.|A:Global6/2 and labels are not printed by hints.|A:Repair binds local labels to atom connectivity.|A:16 valence=6sigma pairs+2pi pairs independently reconciles count.|A:Sigma equals drawn-line-count is a plausible counting misconception.|A:Propyne/ethyne repeats discriminate wrong component rule from one addition slip, conditionally.|A:Connected-pair rule and explicit pi excess restore valid accounting.',
  'A:Flags terminal occupancy absent from single-double drawing.|P:Formal versus physical charge is accurate but an extension beyond requested picture.|A:Separate ledgers leave original representation/count.|A:Correct carbonate contributor charges and lone-pair counts.|P:No sigma/perpendicular frame or unfilled centre-to-function correspondence.|W:Third completed delocalised diagram would answer original construction.|A:Six-electron result and final picture remain protected.|P:Repair is relevant but anchor emphasizes electron/charge ledger rather than constructing requested picture.|A:24=18+6 valid; charge partition caveat scientifically bounded.|P:Omitted pairs align target; measured formal-charge misconception is ancillary.|P:One pair plus two pairs cue arithmetic answer; add changed representation/invariance test.|P:Valid charge distinction does not itself establish orbital-picture reconstruction.',
  'A:Separates fixed axis from all molecular interactions.|A:Relative alignment is general bridge without quantitative barrier.|A:Relative rotation and bounded inference leave comparison.|A:Actual ethane/ethene structures supplied.|P:No fixed-axis initial/twisted direction frame demonstrates geometric bridge.|W:Completed twist consequence would settle comparison; neutral axis frame useful.|A:Precise overlap contrast remains learner work.|A:Repair qualifies sigma persistence and other interactions.|A:Fixed axis does not fix C-H orientations; independent bounded check.|A:Whole-molecule all-overlap-unchanged is plausible overextension.|A:Ethane versus ethene tests generalized orientation criterion, conditionally.|A:Bounded axial sigma/pi distinction avoids exclusively steric energy account.',
  'A:Path tracing rather than counting double bonds targets crux.|R:Explicit saturated-sp3 pathway interruption directly gives asked structural feature.|A:Mark availability then adjacency leaves construction if earlier hint repaired.|A:Correct four-carbon versus five-carbon connectivity.|P:No empty p-availability/path slots demonstrate mapping bridge.|W:Full final p path would answer asked identification.|R:Hint2 supplies requested interruption cause.|A:Exact repair ties saturated interruption to model limit.|A:Replaced suitable unsaturated bridge checks change of continuity.|A:Proximity repairs missing contiguous path is plausible misconception.|A:Comparative pathways can separate repeated proximity criterion from one mark slip, conditionally.|A:Bounded path rule does not assert zero interaction of every quantum kind.',
  'A:Local procedure plus compatibility matches requested synthesis.|A:Distinct count/orientation/applicability jobs bridge procedure design.|A:Ordered atom-by-atom inventory leaves learner procedure.|A:Propyne and allene are correct supplied structures.|P:No empty per-atom procedure ledger presents bridge visually.|W:Third completed ledger would answer procedure examples.|A:Whole procedure and mixed labels retained for learner.|A:Repair explains atom-local ledgers and model boundaries.|A:Allene/propyne local outputs and basis conservation check procedure.|A:Whole-molecule single label is exact contextual wrong procedure.|A:Two mixed-label molecules test persistent whole-molecule attribution, conditionally.|A:Local inventory plus orientation/applicability replaces invalid global label.'
 ],
 'D4': [
  'A:Inventory/model conflict made explicit.|A:Model basis versus physical cause is general epistemic bridge.|A:Sigma/donor/acceptor accounting leaves qualified model choice.|A:Correct formamide connectivity/lone pair.|P:No unfilled sigma/donor-function allocation table demonstrates reconciliation.|W:Completed sp2/p model would settle requested choice; neutral ledger useful.|A:Specific sp2-like allocation retained for learner.|A:Exact amide repair teaches alignment and four-entry boundary.|A:Removing label while retaining mechanism tests label-as-cause.|A:Four entries overrule supplied donation is plausible wrong criterion.|A:Adjacent versus spacer cases test repeated criterion, conditionally.|A:Bounded donor model and nonunique basis caveat address conflict.',
  'A:Preserving connectivity/inventories frames task.|A:Torsion versus inventory distinction is valid general invariant.|A:Fixed carbonyl and declared C-N axis leave actual donor sketch.|A:Correct formamide structural givens.|P:No blank fixed carbonyl/donor-axis two-view reference shown.|W:Third completed90-degree drawing would perform original target.|A:Requested original two-view correspondence remains learner work.|P:Exact repair/anchor predominantly checks18/24 arithmetic rather than geometric construction.|A:Electron sums correct; geometric alignment explained in route but check is ancillary.|P:Electron-loss misconception only covers secondary invariant, not principal representation error.|P:Count-only probe cannot distinguish wrong donor axis from successful geometric reconstruction.|P:Add changed-angle sketch/correspondence check; inventory alone is insufficient repair.',
  'A:Mechanism rather than changing label targets explanation.|A:Alignment variable/model evidence distinction is useful.|A:Geometry-to-overlap plus evidence tagging leaves chain.|A:Correct formamide geometry is oriented without final donor sketch.|P:Repeated structure/directive lacks initial/twisted orientation bridge.|W:Further completed geometry would supply explanatory outcome; neutral comparison frame useful.|A:Supplied trend is already given, hints do not add numerical strength.|A:Repair binds labels to mechanistic alignment conditions.|A:Retaining orientation while removing label is valid causal-slogan test.|A:Label substitutes for mechanism is exact wrong idea.|A:Same-label different alignment tests causal substitution, conditionally.|A:Qualified overlap account excludes barrier inference from sketch.',
  'A:Decision procedure with applicability failure matches prompt.|A:Local count and continuous path are independent familiar checks.|A:Counterfactual is left to learner.|A:Actual A/B connectivity distinguishes spacer honestly.|P:No empty per-site locality/adjacency/alignment table demonstrates bridge.|W:Completed A/B procedure would settle requested application.|A:Interruption is stem-supplied; support asks framework/counterfactual beyond given.|A:Repair explains path and distinguishes folding from structural change.|A:Suitable unsaturated bridge/removing spacer is a valid reassessment check.|A:Proximity equals connected p path is exact contextual error.|A:Folding versus removing spacer tests held criterion, conditionally.|A:Bounded ordinary pathway rule avoids zero-all-interaction claim.',
  'A:Tests uniqueness rather than recalls one angle.|A:Shared domain classification fact is already supplied by stem.|A:Counterexample and evidence qualification leave replacement rule.|A:CH4/NH3/H2O actual connected atom counts supplied.|P:No blank geometry/domain/label comparison table demonstrates bridge.|W:Completed qualified claim would answer task; empty table useful.|A:Specific replacement/evidence choices retained for learner.|A:Repair distinguishes atom-only shape from domains and amide boundary.|A:4/3/2 bonded atoms refute one-label-one-shape; independent boundary sensible.|A:Unique-angle/unique-basis inference is exact audited wrong claim.|A:CH4/H2O comparison can expose repeated overclaim, conditionally.|A:Qualified model plus evidence limit replaces unique-angle slogan.',
  'A:Recall versus applicability distinction identifies target.|A:Locality assumption is legitimate general bridge.|A:Inspect supplied evidence before applying rule leaves conditions judgment.|A:A/B supplied structures orient referenced Q4.|P:No empty applicable/inadequate/evidence table supports conditional classification.|W:Further completed conditions list would perform target; neutral table adequate.|A:Specific applicability decision remains learner work.|A:Repair ties ordinary local ledger to acceptor/alignment conditions.|A:Same formal entry/different orbital role checks count sufficiency.|A:Recall proves applicability is exact contextual misconception.|A:Same count/different adjacency tests wrong sufficiency rule, conditionally.|A:Conditional scope and evidence limits restore qualified rule.',
  'A:Occupancy and geometry both read from supplied model.|A:SOMO versus empty/pair distinction is a familiar rule; one electron already given.|A:Inventory before sketch leaves representation construction.|A:CH3 radical dot and connectivity correspond to givens.|P:No empty sigma/perpendicular occupancy ledger or sketch coordinate frame.|W:Third completed SOMO sketch would answer target.|A:Supplied single occupancy is authentic given, not an added original answer.|A:Repair binds four-function allocation and7-electron ledger.|A:7-6=1 versus cation6-6=0 independently checks occupancy.|A:Three bonds imply empty p is exact audited misconception.|A:Radical/cation cases distinguish occupancy rule from corrected arithmetic slip, conditionally.|A:Occupancy step restores bounded supplied-radical model.',
  'A:Separates observation and inferential strength.|A:Nonunique orbital decomposition is a general epistemic bridge.|A:Prediction/alternatives/conditions/limit leaves experiment design.|A:Correct formamide connectivity supplied.|P:No two-hypothesis empty prediction/observation table visualizes bridge.|W:Completed observation/inference choices would answer task; neutral table useful.|A:Particular observations and alternatives remain learner work.|A:Repair explains controlled metrics and independent channels.|P:Check refers to two compatible electronic descriptions without constructing explicit examples.|A:Geometry uniquely measures donation/barrier is exact wrong inference.|A:Geometry versus quantitative barrier information tests repeated inference, conditionally.|A:Evidence/conditions qualification establishes bounded replacement.',
  'A:Execution and energy inference are separated.|A:Overlap is not Hamiltonian/whole energy is a valid general distinction.|A:Compute factors and choose independent term leaves calculations/refutation.|A:Given angle list displayed correctly; no factor values in native SVG.|P:No empty theta/factor table and separate energy ledger demonstrates translation.|W:Third completed cosine plot would answer calculation; blank axes useful.|A:Specific1,1/2,0 and total-energy counterexample retained for learner.|P:Two-level/weak-coupling transfer is advanced beyond shown prerequisite construction.|A:Fixedtheta independent energy counterexample valid; eigenvalue derivation agrees.|A:Overlap factor equals total energy is exact conflation.|A:Fixedtheta/changed energy term diagnoses repeated variable conflation, conditionally.|P:Correct model limit; teach weak nondegenerate coupling assumptions before demanding that transfer.',
  'A:Universal rule audit across distinct boundaries matches target.|A:Count/role/geometry/evidence distinction provides general bridge.|A:Tests retain learner conditional framework and stop condition.|A:NH3/allene/amide/spacer structures correspond to supplied cases.|P:No empty case-by-explanatory-job decision table visualizes synthesis.|W:Third completed framework would settle synthesis; blank table useful.|A:Final qualified procedure remains learner work.|A:Exact repair explains distinct explanatory jobs.|A:Radical changed occupancy is an appropriate extra-case framework check.|A:Label explains everything is exact audited slogan.|A:Cross-case different mechanisms test repeated slogan use, conditionally.|A:Conditional framework with evidence stopping branch replaces overgeneralization.'
 ]
}

def blob(path):
    return subprocess.check_output(['git','show',f'{BASIS}:{path}'], cwd=ROOT)

def digest(data):
    return hashlib.sha256(data).hexdigest()

def build():
    instances = []
    bindings = []
    for issue, band in [(36,'D3'),(35,'D3'),(38,'D4'),(37,'D4')]:
        prefix = f'evidence/blueprint-cycles/ISS{issue}'
        bank = json.loads(blob(prefix+'/inputs/owner.bank.json'))
        ledger = json.loads(blob(prefix+'/qrt-repair-ledger.json'))
        rendered = html.fromstring(blob(prefix+'/rendered/core2.html'))
        paths = ['inputs/owner.bank.json','inputs/package.v1.json','rendered/core1a.html','rendered/core2.html','qrt-repair-ledger.json'] + [f'assets/question-{n}-givens.svg' for n in range(1,11)]
        hashes = {p: digest(blob(prefix+'/'+p)) for p in paths}
        bindings.append({'issue':issue,'hashes':hashes})
        for number,(q,worksheet) in enumerate(zip(bank['questions'],ledger),1):
            assert q['id']==worksheet['question_ref']
            notes = NOTES[band][number-1].split('|')
            assert len(notes)==12
            article = rendered.xpath('//article[@id=$qid]', qid=q['id'])[0]
            # Exact render excerpt binding, not a claim of browser interaction.
            render_sha = digest(html.tostring(article))
            decisions = {}
            for facet,note in zip(FACETS,notes):
                code,reason = note.split(':',1)
                authored = worksheet['facets'][facet]['authored_evidence']
                decisions[facet] = {'verdict':STATUS[code], 'reason':reason,
                    'review_question':worksheet['facets'][facet]['review_question'],
                    'authored_evidence_sha256':digest(json.dumps(authored,ensure_ascii=False,sort_keys=True).encode())}
            instances.append({'issue':issue,'question_ref':q['id'],'source_identifier':q['original_identifier'],
                'pair_support_review':f'{band}-Q{number}','independent_derivation':DERIVATIONS[band][number-1],
                'authored_classification':q['extensions']['grade9v3:analysis'],
                'exact_render_article_sha256':render_sha,'facets':decisions})
    counts=Counter(d['verdict'] for x in instances for d in x['facets'].values())
    result = {'schema':'issue29-independent-coaching-review-v1','reviewer_session':'review_d3_d4',
       'basis_commit':BASIS,'scope':'D3 B36->A35 and D4 B38->A37; 40 exact instances, 20 repeated A/B source tasks, 480 bounded facet observations',
       'overall_verdict':'REVISE_AND_REBIND_AFTER_AUTHOR_CHANGES','counts_descriptive_only':dict(counts),
       'method':'Independent derivation and pinned render/embedded-SVG/input semantic inspection; twenty manually authored twelve-facet rows rebound separately to A/B copies. No author verdict or count determines these judgments.',
       'direct_browser_attempt':{'status':'NOT_RUN','reason':'In-app browser rejected file URL; explicit no-workaround restriction respected. This review does not claim direct browser clicking or learner outcome evidence.'},
       'source_state':'Owner raw custody preserved; no independent source-reader B cross-read or empirical value verification implied. OpenStax references inform review, do not promote all existing evidence cards.',
       'golden_comparison':'G-CORE2-R2 protects worked results while leaving original target to learner; G-MATH-LINEAR-CONSTRAINT uses one decision/staged representation and changed-case boundary. Both are unblessed candidates, not acceptance authority.',
       'limitations':['No direct browser interaction verdict from this session.','A/B identical support judgments share one semantic derivation; distinct classifications are preserved below.','No child/teacher outcome study or actual misconception diagnosis; repeated-response patterns are conditional coaching evidence.','Facet template generic misconception and authored contextual wrong idea differ in places; interpret contextual fit rather than asserting exact generic template acceptance.','Design/self-critique separate files not found for these evidence products; package research_contribution and question-owned construction/repair inspected instead.','Source authority, 28-cell calibration and learner publication remain separate.'],
       'classification_reconciliation':[
          'D3 Q1 A JUSTIFY D3 vs B EXPLAIN D2: mixed explain/justify real; basic supplied-equality contradiction supports B lower band, expanded justification can be D3. Do not infer whole-productD3 means everyitemD3.',
          'D3 Q3 A SYNTHESIZE vs B MODEL: local count is APPLY, geometry construction MODEL; coordination alone does not establish novel synthesis.',
          'D3 Q4 A EXPLAIN vs B SYNTHESIZE: EXPLAIN is a defensible primary for connected geometric account, synthesis secondary if genuinely reconstructing constituent models.',
          'D3 Q7 A MODEL vs B REPRESENT: supplied planar/delocalised description translated to diagram is REPRESENT primary, model account secondary.',
          'D3 Q8 A D2 vs B D3: simple sigma/pi contrast isD2; bounded total-energy/other-interaction critique increases model/trap work. Both preserve suppliedquestion.',
          'D3 Q9 A REPRESENT D2 vs B MODEL D3: inspect connectivity/map ppath isrepresentation/model blend; demanding explanation of suppliedtwo structures alone neednotD3.',
          'D3 Q10 A MODEL vs B JUSTIFY: devising procedure isSYNTHESIZE/MODEL; its testing justifies procedure, not pure justification only.',
          'D4 Q1 A JUSTIFY vs B MODEL: choose boundedmodel and reconcilelocal count supportsMODEL/EXPLAIN withJUSTIFY secondary.',
          'D4 Q3 A JUSTIFY vs B EXPLAIN: supplied trend explainedthroughoverlap supportsEXPLAIN primary; warrantauditJUSTIFY secondary.',
          'D4 Q6 A JUSTIFY vs B EXPLAIN bothD3: applicabilityjudgment isnotpureRETRIEVE and supplies no acceptedRETRIEVE-D4 example.',
          'D4 Q9 A JUSTIFY vs B APPLY: originalcosvaluesAPPLY, total-energyinferenceJUSTIFY. Advanced extraHamiltonian math isauthor extension, notoriginalcomputationaldenominator.',
          'ISS38 Q1-5/Q8/Q10 assigns algebra load1 although stemscontainnoalgebra execution; ISS37 zero isdefensible. Representation load1vs2 mustreflectactualrequestedconstruction, notuniformpreset.'
        ],
       'ancillary_findings':[
          {'path':'ISS36 inputs/package.v1.json extensions.grade9v3:purpose_delivery.COMPETITION.items[1]','verdict':'REVISE','finding':'Unsupported -254/-239 numeric hydrogenation values and unique15kJ resonance interpretation; completely-insulating/no-delocalisation statements overclaim ordinary path interruption. Treat authoredexample asillustrative suppliedtoy orsourceground exactspecies/conditions andboundthermochemical inference.'},
          {'path':'ISS36 inputs/package.v1.json extensions.grade9v3:purpose_delivery.COMPETITION.items[0]','verdict':'REVISE','finding':'Axial chirality H/CH3 terminal-substituentcriterion correct. Counterfactual all atomscoplanar falsely includes tetrahedralCH3 hydrogens; qualify idealizedterminal-substituentframework andloss ofaxialstereogenicity.'}
        ],
       'references':[
         {'url':'https://openstax.org/books/chemistry-2e/pages/8-2-hybrid-atomic-orbitals','use':'Orbital basis conservation, local sigma/pi framework and nonidentical sp3-like nuclear angles.'},
         {'url':'https://openstax.org/books/organic-chemistry/pages/2-4-resonance','use':'One electronic state versus physically switching contributor drawings.'},
         {'url':'https://openstax.org/books/organic-chemistry/pages/24-3-basicity-of-amines','use':'Amide lone-pair delocalisation as a boundary to localized amine inventory.'},
         {'url':'https://openstax.org/books/organic-chemistry/pages/14-1-stability-of-conjugated-dienes-molecular-orbital-theory','use':'Source gives -253/-236 and reference-dependent16kJ estimate; multiple orbital contributions and four piMOs, not unique15kJ from oneMO.'}
       ],'exact_artifact_bindings':bindings,'instances':instances}
    (OUT/'review-d3-d4.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({'basis':BASIS,'instances':len(instances),'facets':sum(len(x['facets']) for x in instances),'verdicts':dict(counts)}))

if __name__=='__main__':
    build()
