"""Bind explicitly reasoned independent review notes to saved R4 inputs/renders.

This script does not infer semantic correctness from a lint/browser receipt.
Run once on the named basis; later author repairs require a new review binding.
"""
import hashlib
import json
from pathlib import Path
from lxml import html, etree

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).with_suffix('.json')
BASE = ROOT / 'evidence/blueprint-cycles'

# Each row: independent result, hint judgement, visual bridge needed,
# independent changed-case test, local misconception assessment.
NOTES = {
 'D1': [
  ('Four directions require four independent hybrid functions: one s + three p, conventionally sp3; superscript 3 counts p inputs.', 'H1 separates name from size; H2 conservation is the needed invariant; H3 leaves n and set name to the learner.', 'An unfilled one-s + n-p to n+1-output ledger can show conservation without printing sp3.', 'sp2 must have three outputs and sp two. The changed pair directly falsifies counting only the superscript.', 'The nearby numeral/category confusion is instantiated by treating superscript 3 as total size.'),
  ('HCHO has neighbours H,H,O: three domain directions. Two shared pairs in C=O do not add a second nucleus direction; pi density is not axial.', 'Separate inventories and the shared atom pair supply a valid bridge; circling neighbours leaves the explanation to the learner.', 'A neighbour-versus-shared-pair two-column ledger with one changed single-bond anchor is needed.', 'HCN has H,N neighbours: two carbon directions while C-N contains three shared pairs.', 'The probe diagnoses line counting, but does not distinguish a correct label with no causal explanation from a warranted explanation.'),
  ('CH4 carbon has four bonds and no lone pair, hence four domains, tetrahedral arrangement and introductory sp3.', 'Local count precedes label; hints invoke the supplied rule and require the learner to assign the label.', 'Blank count-to-model ledger should separate bond count, LP count and unfilled model/geometry.', 'CH3Cl and CH2Cl2 still have four bonded carbon neighbours; differing substituents do not create extra directions.', 'Treating Lewis page layout as shape changes the mapping from representation to model; probe tests that mapping.'),
  ('NH3 inventory is three N-H domains plus one N lone pair. Four tetrahedral domain positions contain three nuclei, yielding trigonal pyramidal nuclei.', 'The hints preserve three H and one LP, explain wedge/dash reference and leave the actual depth-coded drawing.', 'An unrelated X-centred four-slot solid/wedge/dash convention anchor with unfilled slots is needed.', 'NH4+ has four H/no N LP: it changes one slot, whereas NH3 must retain three H/one LP. H2O has two H/two LP.', 'An extra H/domain during drawing violates entity/inventory invariance. Probe directly checks this.'),
  ('Requested qualitative domain arrangement is served by VSEPR; detailed overlap requires an orbital model. Neither gives exact experimental angles from count alone.', 'Output-first clarification and scope comparison leave candidate choice and boundary judgement; additional ISS32 changed-task hints do not settle original choice.', 'Blank candidate/output scope comparison can make fit and unresolved output explicit.', 'Axial overlap asks for orbital participation, while geometry asks domain/nuclear arrangement. Pi orientation also requires orbital description.', 'Keyword-driven model choice is the local failure; ISS31 MODEL criteria fit. ISS32 JUSTIFY generic proof criterion is not directly diagnosed.'),
  ('A is sigma under supplied axial/end-on description; B is pi under lateral overlap with a nodal plane containing the internuclear axis.', 'Axis reference and orientation features are suitable clues; final two labels remain to assign.', 'Show the common axis with axial and lateral density outlines labelled A/B, no sigma/pi conclusion.', 'Rigidly rotating the whole scene preserves overlap class; rotating one p relative to another may change overlap.', 'Page orientation confusion is a meaningful classification error; ISS31 RETRIEVE can cover it, while ISS32 EXPLAIN missing-warrant criterion is not tested.'),
  ('CH4 has four noncoplanar tetrahedral C-H directions. A valid projection retains four bonds with an explicit depth convention; projected angles need not equal physical angles.', 'Hints preserve connectivity and require toward/away/in-plane meanings; no final target drawing is supplied.', 'A toy X-centred depth legend is needed to demonstrate how page marks represent depth.', 'Rotating paper changes projection, not connectivity or model. Lewis cross alone cannot establish square-planar CH4.', 'Surface-layout copying changes geometric meaning; probe separates page projection from physical structure.'),
  ('At N in NF3, three N-F bonds + one N LP = four domains. Nine terminal F LPs remain at F and do not add N domains.', 'Selected counting centre and separate terminal inventories correctly bound the rule; final tally is left.', 'Two atom-local circles and blank bond/LP tallies can demonstrate locality rather than repeat the instruction.', 'NH3 and NF3 both have four N domains; exchanging H/F changes terminal electronic inventories, not N domain count.', 'A local rule applied to whole-molecule LPs is a scope/mapping failure; changed cases test scope.'),
  ('Faulty ledger treats the two C=O lines as independent neighbour directions. Correct HCHO C inventory is H,H,O, three domains.', 'Hints ask the learner to locate the operation error and build a neighbour-only ledger, rather than copy a corrected answer.', 'Compare the supplied wrong line-count ledger with an unfilled neighbour ledger.', 'HCN carbon has two directions despite a triple bond; CO2 has two despite two double bonds.', 'Local line-count diagnostic is sound, but does not diagnose merely labelling/restating without an explanatory link.'),
  ('BF3 B has three directions -> sp2, three hybrid outputs; CH4 C has four -> sp3, four outputs. Valence 2s/2p inputs conserve dimension.', 'Hints isolate notation and require separate input/output ledgers; matching labels remains learner work.', 'Two unfilled domain/input/output rows can show the correspondence without completed models.', 'sp = one s + one p -> two outputs provides an independent third case; sequence is 2,3,4.', 'Superscript-as-total is a count mapping failure; ISS31 APPLY fits. ISS32 SYNTHESIZE independent-piece criterion is not diagnosed.')
 ],
 'D2': [
  ('BF3 B: three bonds/no LP -> three domains, introductory sp2, planar nuclei. NH3 N: three bonds/one LP -> four domains, sp3-like, pyramidal nuclei.', 'Full inventory clarification and LP bridge explain why the shared sigma count is insufficient; totals/model assignments remain learner work.', 'Bonded-neighbour/central-LP columns with blank totals and labels can show the omitted variable.', 'BF3,NH3,H2O totals are 3,4,4 and bonded nuclei 3,3,2; equal bond counts need not imply equal total domains.', 'Bonds-only probe tests an omitted domain; it does not test a label-only answer with missing explanatory warrant.'),
  ('HCHO C has three domains -> three sp2 directions plus one residual p. C=O has one sigma/one pi; four valence functions are not reused.', 'Hints distinguish orbital budget from domains/bond components; H2 gives a principle, H3 leaves mapping to explicit roles.', 'Four-input budget with unfilled hybrid/residual columns is needed to demonstrate nonduplication.', 'sp carbon has two hybrids/two residual p; sp2 three/one. Both totals are four, not five.', 'Double spending violates representational invariance (ISS33) or variable mapping (ISS34); both are concrete demand failures.'),
  ('Each ethene carbon has three coplanar sigma directions and one perpendicular p; the two p axes are parallel for lateral pi overlap, node in molecular plane.', 'The hints establish molecular-plane reference and leave the two-centre overlap drawing; they do not provide the completed ethene diagram.', 'A changed toy plane/reference plus an unfilled second centre can demonstrate reference and orientation without drawing completed ethene.', 'Rigid picture rotation preserves relative p alignment; twisting one CH2 changes alignment and can reduce pi overlap, with no numeric barrier inferred.', 'Confusing page and relative orbital orientation changes representational meaning; diagnostic checks the preserved invariant.'),
  ('CO2 C has two O-neighbour domains -> linear sp framework, two sp sigma roles/two residual p roles, two sigma/two pi components. C-O axes are collinear; residual p orientations perpendicular.', 'Hints separate ledgers and bound localized VB claims; final consistent allocation remains to construct.', 'Two axial job placeholders plus unfilled residual-p/bond-component ledger can demonstrate joint accounting.', 'HCN carbon and ethyne carbon likewise conserve two sp + two residual p = four. Carbon basis count cannot establish a unique terminal O plane.', 'Independent component ledgers must reconcile to four carbon functions; double-counting is a concrete invalid coordination of pieces.'),
  ('Three sigma bonds alone cannot imply sp2: NH3 also has an N LP and four domains. Rule needs total local domains and introductory-model boundary; geometry does not uniquely measure hybrid coefficients.', 'Counterexample definition and three-bond/LP test leave judgement and warrant; epistemic boundary is appropriately in protected reasoning.', 'Two candidate inventories with blank claim/warrant/omitted-condition fields would show why the same antecedent yields different totals.', 'Three-bond N with LP has four domains; three-bond B without LP has three. Universal rule fails under supplied model.', 'Local probe refutes a bonds-only universal claim, but does not separately test treating geometry observation as direct proof of an orbital basis.'),
  ('CH3F has four carbon neighbours, four domains, introductory sp3. Substituent identity can change bond properties without adding a neighbour direction.', 'Count versus property distinction is valid; hints avoid unprovided bond lengths/angles and leave count/model assignment.', 'Parallel CH4/CH3F neighbour inventories with blank totals and unresolved-property fields can demonstrate the invariant.', 'CH4,CH3F,CH2F2 all have four carbon neighbours. F does not create a second domain beyond C-F.', 'Property/count conflation is local and useful, but literal EXPLAIN missing-warrant criterion remains untested.'),
  ('HCN C has H,N directions; N has C direction plus LP: both two domains/sp. C-N triple contains one sigma/two pi. Four shared pairs + N LP = ten valence electrons.', 'Hints separate two atom-local counts from bond components and preserve final explicit allocations.', 'Separate C,N local ledgers plus blank C-N sigma/pi columns are needed.', '1+4+5=10 electrons: C-H pair (2), C-N three pairs (6), N LP (2). No extra directions arise from multiplicity.', 'Multiplicity-to-domain confusion violates local mapping (ISS34) and consistency of component/local ledgers (ISS33).'),
  ('Methylamine C has 4 bonds/0 LP -> sp3 and tetrahedral nuclei. N has 3 bonds/1 LP -> sp3-like and pyramidal nuclei. The LP is absent from nuclear shape naming.', 'Atom-local inventories and domain-versus-nucleus distinction make the key comparison, leaving separate shapes to learner.', 'C,N columns for bond/LP/domain/nuclear inventories can demonstrate shared total versus different occupied nuclear slots.', 'Replacing N-H with N-CH3 in neutral secondary amine preserves 3 bonds/1 LP. No exact angle is implied.', 'Whole-molecule label misuse is local; probe does not distinguish merely giving two correct shape labels without explaining why.'),
  ('Carbon basis one 2s + three 2p -> three sp2 hybrids/one residual perpendicular p. Hybrids address three sigma directions, remaining p the pi role; total four.', 'The basis invariant and no-double-spending rule are valid; final arrangement and allocation remain to express.', 'Unfilled four-function allocation budget can demonstrate that hybrid inputs cannot also be counted as residual functions.', 'sp,sp2,sp3 hybrid/residual allocations are 2+2,3+1,4+0. A five-orbital ledger is impossible for this basis.', 'Duplicated basis functions violate entity/invariant preservation in representation; the allocation probe directly diagnoses that.'),
  ('CH4/NH3/H2O all have four domains, but bonded nuclear inventories 4/3/2 give tetrahedral/pyramidal/bent shapes. Therefore domain geometry does not entail one nuclear shape.', 'Domain/nucleus distinction and fixed total leave counterexample judgement and shape assignment.', 'All-domain slots versus bonded-nucleus positions ledger can demonstrate the omitted slots.', 'No-LP centre has all four nuclear vertices; one/two LPs remove nuclear vertices while retaining four domains.', 'Diagnostic checks conflated names but not reliance on an example as proof of a universal rule; protected reasoning does provide a valid counterexample warrant.')
 ]
}

rows=[]
hashes={}
for issue in [32,31,34,33]:
 p=BASE/f'ISS{issue}'
 bank=json.loads((p/'inputs/owner.bank.json').read_text(encoding='utf-8'))
 ledger=json.loads((p/'qrt-repair-ledger.json').read_text(encoding='utf-8'))
 pages={core:html.fromstring((p/f'rendered/{core}.html').read_bytes()) for core in ['core1a','core2']}
 for name in ['inputs/owner.bank.json','inputs/package.v1.json','rendered/core1a.html','rendered/core2.html','qrt-repair-ledger.json']:
  file=p/name; hashes[str(file.relative_to(ROOT)).replace('\\','/')]=hashlib.sha256(file.read_bytes()).hexdigest()
 for n,(q,worksheet) in enumerate(zip(bank['questions'],ledger),1):
  group='D1' if issue in [32,31] else 'D2'
  result,hints,visual,check,misconception=NOTES[group][n-1]
  article=pages['core2'].xpath('//*[@id=$qid]',qid=q['id'])[0]
  links=article.xpath('.//a[contains(@href,"repair-")]/@href')
  anchor=links[0].split('#',1)[1]
  target=pages['core1a'].xpath('//*[@id=$anchor]',anchor=anchor)
  if len(target)!=1: raise ValueError((issue,n,'repair target'))
  svg=p/f'assets/question-{n}-givens.svg'
  hashes[str(svg.relative_to(ROOT)).replace('\\','/')]=hashlib.sha256(svg.read_bytes()).hexdigest()
  generic_m_request = (group=='D1' and n in [2,9]) or (group=='D1' and issue==32 and n in [5,6,10]) or (group=='D2' and n in [1,5,6,8,10])
  facets={}
  for key in ['H1','H2','H3']:
   idx=int(key[-1])-1
   facets[key]={'verdict':'PASS_BOUNDED_SEMANTIC','reason':hints,'observed':q['scaffolds'][idx]['text']}
  facets['S1']={'verdict':'PASS_BOUNDED_SEMANTIC','reason':f'SVG keeps supplied {q["original_identifier"]} situation/connectivity and warns that page angles are not measured geometry; requested conclusion is not printed.', 'asset':str(svg.relative_to(ROOT)).replace('\\','/')}
  facets['S2']={'verdict':'REQUEST_CHANGES','reason':'BRIDGE repeats GIVENS marks and appends an instruction; it does not demonstrate the required held-idea bridge visually. '+visual}
  facets['S3']={'verdict':'NOT_APPLICABLE_CONDITIONAL_WAIVER','reason':'Two stages can suffice and a completed target third stage would answer the task. This does not compensate for missing S2; reassess the waiver after S2 repair.'}
  facets['P1']={'verdict':'PASS_BOUNDED_SEMANTIC','reason':'Hints and givens leave final requested '+result.split('.')[0]+' as learner work. Final explanation and rationale are template-protected in saved HTML. No separate interactive exposure audit performed here.'}
  facets['P2']={'verdict':'PASS_SEMANTIC_TARGET_ONLY','reason':'Saved repair link resolves exactly once in Core1A and question-local clinic teaches the reviewed clarification/connection/rule. Click/focus/reload mechanics are outside this independent semantic verdict.', 'link':links[0]}
  if (group=='D1' and n==8) or (group=='D2' and n in [2,7,9]):
   facets['P2']['verdict']='REQUEST_CHANGES_CONCEPTUAL_VISUAL'
   facets['P2']['reason']='Exact repair clinic is question-local, but ordinary concept construction still binds an incompatible species/basis visual: NF3 Q8 uses HCHO; D2 HCHO Q2, HCN Q7 and generic sp2 Q9 use CO2 sp accounting. A changed example must be labelled and its invariant correspondence taught; current construction text presents the actual question while visual depicts another centre.'
  facets['P3']={'verdict':'PASS_BOUNDED_SEMANTIC','reason':result+' Independent changed-case derivation: '+check, 'solution_summary':q['answer']['summary']}
  for key in ['M1','M2','M3']:
   facets[key]={'verdict':'REQUEST_CHANGES_GENERIC_CRITERION' if generic_m_request else 'PASS_BOUNDED_SEMANTIC', 'reason':misconception+' Local diagnostic mathematical/scientific result: '+check, 'criterion':worksheet['facets'][key]['review_question'], 'observed':q['extensions']['grade9v3:learning_repair'][{'M1':'wrong_idea','M2':'probe','M3':'rule'}[key]]}
  rows.append({'issue':issue,'question_ref':q['id'],'label':q['original_identifier'],'independent_derivation':result,'changed_case_derivation':check,'facets':facets,'authored_analysis':q['extensions']['grade9v3:analysis']})

report={
 'schema':'independent-academic-review-v1', 'reviewer':'separate Codex session /root/review_d1_d2',
 'basis_head':'59cfb081a96b6d15ad9c5a6ded771b2dce00091d',
 'scope':'40 D1/D2 product-question instances (20 distinct owner questions), 480 recorded facet decisions, not 480 accepted facets.',
 'method':'Read exact saved Core2 and Core1A HTML, inert protected blocks, question SVGs, authored inputs and literal worksheet criteria; independently derived results above. Paired B/A arguments intentionally reuse the same chemistry only after inspecting both instances. Did not use author academic verdicts or browser PASS to infer correctness.',
 'source_support':['https://openstax.org/books/chemistry-2e/pages/8-2-hybrid-atomic-orbitals','https://openstax.org/books/chemistry-2e/pages/8-3-multiple-bonds','https://openstax.org/books/chemistry-2e/pages/7-6-molecular-structure-and-polarity'],
 'limits':['Semantic HTML/SVG inspection only; no separate browser clicking or screenshot render in this reviewer session.','OpenStax reference check supports bounded introductory models; it does not certify original source-card custody, item transcription or a second source-reader cross-read.','No learner response collection, psychometric difficulty validation, Owner acceptance, full six-Core family closure or all-subject acceptance.','Question-instance facets are not independent learner outcomes; paired products share twenty questions.'],
 'hashes':hashes, 'question_reviews':rows,
 'findings':[
  {'id':'D1D2-S2','severity':'P2','issue':[32,31,34,33],'reason':'All twenty distinct native BRIDGE scenes repeat givens and add text; they lack the visual bridge required by S2. Forty product instances need revision/review.'},
  {'id':'D1D2-M-GENERIC','severity':'P2','reason':'Several literal demand-level M criteria are not instantiated by local scientific diagnostics. Valuable line-count/LP probes do not measure whether a learner merely labels an EXPLAIN result without a warrant. Do not equate local misconception support with literal generic facet acceptance.'},
  {'id':'D2-CO2-BASIS','severity':'P2','issue':34,'question':'Q4','reason':'Analysis basis says two orthogonal C=O double bonds. Linear CO2 C-O bond axes are collinear; residual carbon p orientations are mutually perpendicular. Authored explanation is correctly bounded but this protected metadata is misleading.'},
  {'id':'D1D2-CORE1A-VISUAL','severity':'P2','reason':'ISS32/31 Q8 construction uses REP-CHE-DOMAINS-HCHO; ISS34/33 Q2/Q7/Q9 uses REP-CHEM-CO2-PI-ORTHOGONAL despite local rewritten text. Question-local repair clinic is coherent, ordinary concept construction remains mismatched. Eight P2 verdicts request changes.'},
  {'id':'CLASSIFICATION-DISAGREEMENTS','severity':'REVIEW_NOTE','reason':'Frozen metadata disagreements: ISS32 Q5 should have MODEL primary/justify secondary, matching ISS31. ISS32 Q6 is defining classification RETRIEVE, matching ISS31, rather than EXPLAIN primary. ISS32 Q10 supplied table matching is APPLY rather than SYNTHESIZE. ISS33 Q2 assignments/decomposition do not explicitly ask a diagram, so APPLY primary is preferable to REPRESENT. ISS33 Q7 inventory is routine APPLY with explanation rather than genuine SYNTHESIZE. Keep frozen metadata/custody and report calibration disagreement.'},
  {'id':'COMPONENT-DISAGREEMENTS','severity':'REVIEW_NOTE','reason':'Same stems have inconsistent B/A components: D1 Q5 scored6/D3 versus4/D2; direct scope choice supports model2+trap1+chain1=4/D2, without explicit new representation translation/extended chain. D1 Q6 defining classification supports representation1 and little/no novel chain, total1/D1 rather than3/D2. D1 Q10 supplied two-row table routine model1+chain1=2/D1 rather than representation1 additionally=3/D2. D2 Q9 carbon-to-orbital translation needs more than0 model selection and1 translation; ISS33 score5 is defensible; actual learner calibration unmeasured.'}
 ],
 'conclusion':'REQUEST_CHANGES; bounded chemical derivations are coherent, but S2, generic M mapping and one CO2 metadata claim prevent claiming complete independent facet acceptance.'
}
OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'path':str(OUT),'instances':len(rows),'facets':sum(len(r['facets']) for r in rows),'hashes':len(hashes)}))
