#!/usr/bin/env python3
"""Package precompiled CoreProjection rows for the static learner proof.

Issue #175 owns browser/runtime composition, not academic compilation. Until the
#173/#174 provider is landed on this branch, this generator deliberately consumes
only the frozen precompiled projection fixture used by the learner-shell contract.
It must not read subject libraries, matrices, teaching routes or raw Topic Atlas
records to reconstruct Core semantics.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PROVIDER_FIXTURE = REPO / "tests" / "fixtures" / "workbench" / "core-learning-projections.json"
OUT = REPO / "public" / "core-learning" / "data.js"


class CoreLearningDataError(ValueError):
    pass


def _precompiled_rows(path: Path = PROVIDER_FIXTURE) -> list[dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload.get("projections")
    if not isinstance(rows, list) or not rows:
        raise CoreLearningDataError("CORE_LEARNING_PRECOMPILED_PROJECTIONS_REQUIRED")

    normalized = []
    seen = set()
    for index, projection in enumerate(rows):
        if not isinstance(projection, dict):
            raise CoreLearningDataError(
                f"CORE_LEARNING_PRECOMPILED_PROJECTION_INVALID: {index}"
            )
        projection_id = projection.get("id")
        contract_version = projection.get("contract_version")
        core = projection.get("core")
        if (
            not isinstance(projection_id, str) or not projection_id.strip()
            or contract_version != "1.0"
            or core not in {"CORE1A", "CORE1B", "CORE2A", "CORE2B"}
        ):
            raise CoreLearningDataError(
                f"CORE_LEARNING_PRECOMPILED_PROJECTION_INVALID: {index}"
            )
        if projection_id in seen:
            raise CoreLearningDataError(
                f"CORE_LEARNING_PRECOMPILED_PROJECTION_DUPLICATE: {projection_id}"
            )
        seen.add(projection_id)
        normalized.append({
            "id": f"fixture:{projection_id}",
            "subject": "Fixture",
            "source_ref": projection_id,
            "projection": projection,
            "scene_ref": None,
            "adapter_ref": None,
            "injection_refs": [],
        })
    return normalized


def build() -> dict:
    return {
        "generated_by": "Shared/tools/build_core_learning_data.py",
        "provider_status": "FROZEN_PRECOMPILED_FIXTURE",
        "core_projections": _precompiled_rows(),
    }


def render(payload: dict) -> str:
    return (
        "// Generated by Shared/tools/build_core_learning_data.py -- do not edit by hand.\n"
        "window.GRADE9V3_CORE = "
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + ";\n"
    )


def rendered_file() -> dict[str, bytes]:
    return {OUT.relative_to(REPO).as_posix(): render(build()).encode("utf-8")}


def write() -> dict:
    payload = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(payload), encoding="utf-8", newline="\n")
    return payload


def main() -> int:
    payload = write()
    print(
        f"wrote {OUT.relative_to(REPO)}: "
        f"{len(payload['core_projections'])} precompiled fixture projection(s)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
