#!/usr/bin/env python3
"""Build the small static supplement consumed by the Core Prompt Composer.

The normal public/data/data.js remains the browser authority for canonical matrices,
capabilities and top-level library questions. This supplement exists only because
nested exam-bank questions are deliberately outside that existing web projection.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if __package__ in (None, ""):
    sys.path.insert(0, str(REPO))

from Shared.contracts import load  # noqa: E402

OUT = REPO / "public/data/prompt-composer-data.js"
SNAPSHOT = REPO / "relay/GENERATED/tasks/ISSUE-272.snapshot.yaml"


def subjects(repo: Path = REPO) -> list[str]:
    return sorted(p.parent.parent.name for p in repo.glob("*/adapter/CoreContracts.json"))


def planning_basis(repo: Path = REPO) -> str:
    try:
        snapshot = json.loads((repo / SNAPSHOT.relative_to(REPO)).read_text(encoding="utf-8"))
        base = ((snapshot.get("material") or {}).get("base"))
        if base:
            return f"main@{base}"
    except (OSError, json.JSONDecodeError):
        pass
    return "UNRESOLVED_REPOSITORY_BASIS"


def build(repo: Path = REPO) -> dict:
    template = load(repo / "template/core-prompt-composer/core-agent-prompt.v1.json")
    payload = {
        "generated_by": "Shared/tools/build_prompt_composer_data.py",
        "contract_version": "1.0.0",
        "repository_basis": planning_basis(repo),
        "template": template,
        "subjects": {},
    }
    for subject in subjects(repo):
        questions = {}
        library = repo / subject / "library"
        for path in sorted(library.glob("*/*.json")):
            package = load(path)
            for q in package.get("questions", []):
                ext = q.get("extensions") or {}
                questions[q["id"]] = {
                    "id": q["id"],
                    "status": q.get("status"),
                    "primary_capability_ref": q.get("primary_capability_ref"),
                    "secondary_capability_refs": list(q.get("secondary_capability_refs") or []),
                    "analysis": ext.get("grade9v3:analysis"),
                    "source_custody": ext.get("grade9v3:source_custody"),
                }
        payload["subjects"][subject] = {"nested_questions": dict(sorted(questions.items()))}
    return payload


def render(payload: dict) -> str:
    return (
        "// Generated by Shared/tools/build_prompt_composer_data.py -- do not edit by hand.\n"
        "window.GRADE9V3_PROMPT_COMPOSER = "
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + ";\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    intended = render(build())
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != intended:
            print(f"generated file is stale: {OUT.relative_to(REPO)}")
            print("Regenerate with: python3 Shared/tools/build_prompt_composer_data.py")
            return 1
        print(f"prompt composer data up to date: {OUT.relative_to(REPO)}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(intended, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
