#!/usr/bin/env python3
"""Generate learner CoreProjection rows from canonical compiler output."""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from Shared.contracts import ContractError
from Shared.library.compile_inputs import compile_bucket
from Shared.library.resolve import build_index, load_packages
from Shared.tools.core_learning_projection_adapter import adapt_compiled_bucket_with_status

OUT = REPO / "public" / "core-learning" / "data.js"


def subjects() -> list[str]:
    return sorted(p.parent.parent.name for p in REPO.glob("*/adapter/CoreContracts.json"))


def _subject_rows(subject: str) -> tuple[list[dict], list[dict]]:
    paths = sorted((REPO / subject / "library").glob("*.json"))
    if not paths:
        return [], []
    records = build_index(load_packages(paths))
    bucket_ids = sorted(
        row["id"]
        for row in records.values()
        if isinstance(row, dict) and row.get("_collection") == "buckets"
    )
    rows = []
    availability = []
    for bucket_id in bucket_ids:
        try:
            compiled = compile_bucket(
                records,
                bucket_id,
                topic_id=bucket_id,
                title=records[bucket_id]["title"],
                subject=subject,
                practice_control={"mode": "DESIGN_PREVIEW", "purpose": "PRACTICE"},
            )
        except ContractError as exc:
            availability.append({
                "subject": subject,
                "bucket_ref": bucket_id,
                "status": "UNSUPPORTED",
                "code": exc.code,
                "detail": exc.detail,
                "projection_refs": [],
            })
            continue
        bucket_rows, findings = adapt_compiled_bucket_with_status(compiled, records, subject=subject)
        rows.extend(bucket_rows)
        first = findings[0] if findings else None
        availability.append({
            "subject": subject,
            "bucket_ref": bucket_id,
            "status": "AVAILABLE" if bucket_rows else "UNSUPPORTED",
            "code": first["code"] if first else None,
            "detail": first["detail"] if first else None,
            "findings": findings,
            "projection_refs": [row["id"] for row in bucket_rows],
        })
    return rows, availability


def build() -> dict:
    rows = []
    availability = []
    for subject in subjects():
        subject_rows, subject_availability = _subject_rows(subject)
        rows.extend(subject_rows)
        availability.extend(subject_availability)
    rows.sort(key=lambda row: row["id"])
    availability.sort(key=lambda row: (row["subject"], row["bucket_ref"]))
    return {
        "generated_by": "Shared/tools/build_core_learning_data.py",
        "provider_status": "PRODUCTION_COMPILED_CANONICAL",
        "provider": {
            "mode": "CANONICAL_LIBRARY_TO_COMPILE_BUCKET_TO_CORE_PROJECTION",
            "contract_version": "1.1",
        },
        "core_projections": rows,
        "bucket_availability": availability,
        "findings": [
            {
                "subject": row["subject"],
                "bucket_ref": row["bucket_ref"],
                **finding,
            }
            for row in availability
            for finding in row.get("findings", [])
        ],
    }


def render(payload: dict) -> str:
    return (
        "// Generated by Shared/tools/build_core_learning_data.py -- do not edit by hand.\n"
        "window.GRADE9V3_CORE = "
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + ";\n"
    )


def rendered_file() -> dict[str, bytes]:
    return {OUT.relative_to(REPO).as_posix(): render(build()).encode("utf-8")}


def write() -> dict:
    payload = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(payload), encoding="utf-8", newline="\n")
    return payload


def main() -> int:
    payload = write()
    print(
        f"wrote {OUT.relative_to(REPO)}: "
        f"{len(payload['core_projections'])} canonical compiler projection(s)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
