"""Question-specific routes for cumulative D2-D4 repair, authored support only."""
import argparse
import json
import subprocess
from pathlib import Path
from close_d1 import move, write

ROOT=Path(__file__).resolve().parents[3]
ROUTES={
'D2':[
 [move('Inventory bonds and central lone pairs separately.','The givens supply three bonds at each centre but different lone-pair counts.','BF3: 3+0=3 domains; NH3: 3+1=4.'),move('Apply the bounded introductory domain models.','The local total, rather than bonds alone, selects the model arrangement.','BF3: planar/sp2; NH3: tetrahedral domains/sp3-like.'),move('Name shape using bonded nuclei only.','The N lone-pair domain has no bonded nucleus.','BF3 is trigonal planar; NH3 is trigonal pyramidal.'),move('Compare NH3 with H2O.','Three-bond/one-pair and two-bond/two-pair inventories both total four.','The same domain total can give different bonded-nucleus shapes.')],
 [move('Count C neighbours in HCHO.','Two H and one O are three connections; bond multiplicity is a separate inventory.','Three domains; no C lone pair.'),move('Allocate the four carbon valence functions.','One 2s plus two 2p form three sp2 hybrids, leaving the third 2p unused in that mixing.','Three sigma-direction hybrids plus one residual p.'),move('Resolve the C=O bond components.','A localized double-bond account has one axial sigma and one lateral pi component.','C=O: one sigma + one pi; residual C p supplies the pi role.'),move('Close the basis ledger using an sp comparison.','sp gives two hybrids and two residual p functions from the same four inputs.','Both allocations total four; no p function is spent twice.')],
 [move('Build the two local carbon sigma frames.','Each ethene carbon has three sigma directions and one remaining p function in sp2 accounting.','Two in-plane three-direction frames; one perpendicular p at each C.'),move('Align the p functions relative to the molecular plane.','A residual p is perpendicular to its carbon sigma plane.','Parallel perpendicular p directions in planar ethene.'),move('Draw both axial and lateral overlap.','The C-C sigma component is axial; lateral p overlap lies above and below the plane.','A sigma framework plus a pi component with a node in the molecular plane.'),move('Compare rigid rotation with relative CH2-group rotation.','Only the latter changes relative p alignment.','Whole-picture rotation preserves overlap geometry; relative twisting can reduce pi alignment.')],
 [move('Count two O neighbours at CO2 carbon.','Each C=O multiple bond contributes one local direction.','Two carbon domains; linear introductory framework.'),move('Allocate carbon orbitals without duplication.','One 2s plus one 2p yields two sp hybrids; two p directions remain perpendicular.','Two sigma directions and two residual C p functions.'),move('Account for each localized C=O component.','Two double bonds require two sigma and two pi components in this bookkeeping model.','Two sigma + two pi; all four carbon functions have declared roles.'),move('Bound the inference about terminal oxygen.','A localized basis drawing is one representation of the electronic description; carbon counting does not uniquely measure an oxygen basis.','Linear carbon accounting is consistent; a unique observed O orbital-plane picture is not established.')],
 [move('Hold the claimed three-sigma condition fixed.','Both supplied centres satisfy it, so an omitted lone-pair condition can test the implication.','BF3 and NH3 both have three sigma bonds.'),move('Use nitrogen as the counterexample.','NH3 also has one central lone pair; its local total is four.','Three sigma bonds alone do not imply three domains/sp2.'),move('Replace the claim with a conditional local rule.','Within localized introductory classification, bonds plus central lone pairs determine the domain total.','Use the full inventory: three domains -> sp2 model; four -> sp3-like model.'),move('Separate shape observations from a unique orbital basis.','Nuclear geometry constrains a description but does not measure hybrid coefficients.','The counterexample rejects the bond-only rule without proving unique physical hybrid orbitals.')],
 [move('Recount carbon neighbours after H-to-F substitution.','CH3F has three H and one F directly attached to C.','Four carbon bonding directions.'),move('Apply the same local four-domain allocation.','Changing substituent identity does not itself create a new neighbour or lone pair at C.','Introductory sp3 carbon model.'),move('State what the count leaves open.','Bond lengths, polarity and exact angles require information beyond neighbour counting.','No equality of C-H and C-F properties is inferred.'),move('Test CH2F2 as a changed inventory.','Two H and two F are still four neighbours.','Four domains remain; electronegativity is not an extra domain.')],
 [move('Inventory carbon and nitrogen separately in HCN.','C has H and N neighbours; N has one C neighbour plus one lone pair.','C: two domains; N: two domains.'),move('Allocate each local four-function valence basis.','Two sp hybrids leave two perpendicular p functions at each second-period centre.','Introductory sp at C and N.'),move('Count triple-bond components without adding local directions.','Axial overlap gives one sigma; the two residual p pairs give two pi components.','C-N: one sigma + two pi; C-H adds one sigma.'),move('Close the ten-valence-electron inventory.','H+C+N contributes 1+4+5=10; four shared pairs and one N lone pair use five pairs.','Eight bonding electrons + two lone-pair electrons = ten.')],
 [move('Make atom-local inventories in CH3NH2.','C has four single bonds; N has three single bonds and one lone pair.','C: 4+0; N: 3+1; both total four domains.'),move('Assign the localized introductory domain models.','Each four-domain centre can use sp3-like accounting under the stated local model.','Four model directions at each centre.'),move('Count nuclei for the separate shape descriptions.','C has four bonded neighbours while N has three; a lone pair is not an atomic vertex.','Tetrahedral C nuclear arrangement; pyramidal N arrangement.'),move('Replace an N-H bond with an N-CH3 bond in a neutral amine comparison.','The N inventory stays three bonds plus one lone pair.','Local N count and pyramidal introductory description persist; exact angle is unresolved.')],
 [move('Start from four carbon valence-basis functions.','The second-period basis is one 2s plus three 2p.','Four inputs; three sigma directions and one pi role required.'),move('Mix only the functions assigned to sigma directions.','One s plus two p makes three in-plane sp2 hybrids.','Three hybrids; one p remains outside the mixing.'),move('Assign the residual p to the pi role.','It is perpendicular to the sigma plane and can overlap laterally with a suitable neighbour.','Three sigma hybrids + one residual perpendicular p.'),move('Check against sp and sp3 allocations.','Those alternatives account for two hybrids plus two p, or four hybrids plus zero p.','All totals are four; no function is simultaneously a hybrid input and an extra residual p.')],
 [move('Hold the four-domain total fixed across three cases.','CH4, NH3 and H2O have respective bond/pair inventories 4/0, 3/1 and 2/2.','All have four introductory domains.'),move('Use all domains for domain geometry.','Bonding and lone-pair entries occupy the domain-model directions.','Tetrahedral electron-domain arrangement in all three.'),move('Use bonded nuclei for molecular shape.','Removing LP entries from the shape name changes the number of atomic vertices.','CH4 tetrahedral; NH3 pyramidal; H2O bent.'),move('State the condition for the two names to coincide.','When there is no central lone pair every domain direction terminates at a bonded nucleus.','The student claim holds for the no-lone-pair case, not universally.')],
],
'D3':[
 [move('Compare a fixed localized nitrate picture with the supplied equivalence.','A permanently unique N=O position distinguishes one bond; the observation instead supplies three equivalent N-O bonds.','The fixed single/double-bond assignment is inadequate.'),move('Choose one delocalised pi account for all contributors.','The contributors are alternative bookkeeping descriptions of one electronic state, not switching structures.','One delocalised pi system spans the N-O framework.'),move('Specify nitrogen sigma accounting independently.','Three planar local sigma directions support the introductory sp2 framework; equivalence alone is not its criterion.','Three N sigma directions; residual perpendicular p participates in the pi space.'),move('Test the equivalence-implies-sp2 inference on NH3.','NH3 can have three equivalent N-H bonds while having four local domains.','Bond equivalence does not uniquely select an sp2 description.')],
 [move('Preserve the nitrate nuclei and sigma connectivity.','Every supplied contributor has the same N centre and three N-O connections.','Three coplanar N-O sigma directions.'),move('Build a perpendicular p basis across all four centres.','A delocalised qualitative diagram combines the central N and three O p functions.','Four perpendicular p functions spanning one pi space.'),move('Count pi-space electrons from one contributor.','One N=O pi pair and p-oriented pairs on the two singly bonded O sites supply three pairs.','Six pi-space electrons; the Lewis double bond alone is not the complete pi inventory.'),move('Check contributor invariants rather than a switching animation.','Changing the drawn N=O position changes bookkeeping, not nuclei, total charge or electron number.','One planar equivalent-bond state; no molecule oscillating between three structures.')],
 [move('Count local sigma-neighbour directions in allene.','Each terminal carbon has two H plus the central C; the central carbon has two terminal-C neighbours.','Terminals: three directions; centre: two.'),move('Allocate the local valence bases.','Terminal sp2 leaves one p each; central sp leaves two mutually perpendicular p functions.','sp2-sp-sp2 along the carbon chain.'),move('Match the two separate central p directions to terminal p functions.','Each localized pi component needs suitable lateral alignment with its terminal p.','Two orthogonal pi planes.'),move('Deduce and check terminal CH2 planes.','Each terminal sigma plane is perpendicular to its participating p; looking down the chain makes the relation explicit.','Terminal CH2 planes are perpendicular in this introductory model; rigid rotation preserves that relation.')],
 [move('Construct the ethene baseline.','Each carbon uses three planar sigma directions and one residual perpendicular p.','One pair of parallel p functions; a coplanar sigma framework.'),move('Reallocate the central carbon for allene.','Its two sigma-neighbour directions use sp, leaving two perpendicular p functions.','Two independent central p directions rather than ethene\'s single p direction.'),move('Match each terminal p to its corresponding central direction.','The terminal sigma plane is perpendicular to its p, so distinct orthogonal p alignments constrain distinct planes.','Perpendicular terminal CH2 planes.'),move('Reject both a copied planar sketch and the Pauli explanation.','The supplied localized construction requires orthogonal directions; Pauli limits state occupancy, not all multicentre participation of one basis function.','The plane relation follows orbital alignment in this model, not a universal one-bond-per-orbital prohibition.')],
 [move('List the supplied local inventories beside equivalence.','CO2 C has two domains; nitrate N three; NH3 N four although each case has equivalent central bonds.','Two, three and four local totals with equivalence held true.'),move('Use CO2 or NH3 as a counterexample.','One case satisfying the premise but failing the claimed sp2 consequence refutes a universal implication.','CO2 uses introductory sp; NH3 sp3-like; the claim is false.'),move('Separate model labels from observable bond equality.','Domain count and orbital allocation are different layers from measured equivalence.','Only nitrate\'s three-direction planar framework supports the local sp2 description here.'),move('Change to CH4 as an independent test.','Equivalent C-H bonds coexist with four local directions and an sp3 model.','The rejected equivalence-only rule fails a fresh fourth case.')],
 [move('Classify each carbon from its own neighbours in propyne.','CH3 has four directions; both triple-bond carbons have two sigma-neighbour directions.','C labels in order: sp3, sp, sp.'),move('Count sigma components by atom connectivity.','Each connected atom pair has one sigma component regardless of bond order.','Four C-H plus two C-C sigma components = six.'),move('Count the extra components of the triple bond.','A triple bond contains one sigma and two pi components in the introductory account.','Two pi bonds in the whole molecule.'),move('Reconcile local and whole-molecule inventories.','The triple bond connects one neighbour at either end even though it has three components.','Six sigma/two pi globally; two local directions at each sp carbon, with no contradiction.')],
 [move('Preserve carbonate connectivity across contributors.','All contributors use one C centre and three O neighbours with total charge -2.','Three planar C-O sigma directions.'),move('Construct the delocalised pi basis and electron ledger.','Central C plus three O p functions span the pi space; a contributor has one pi pair plus p-oriented pairs at two singly bonded O sites.','Four p functions and six pi-space electrons.'),move('Interpret contributor charge bookkeeping.','Three equivalent contributors average the two formal negative O charges across three sites.','Average formal charge -2/3 per O; this is not a uniquely measured partial charge.'),move('Check why one fixed contributor is incomplete.','A permanently selected C=O position conflicts with the supplied three equivalent C-O bonds.','Use one delocalised description, preserving nuclei, total charge and electron count.')],
 [move('Specify the axial C-C sigma reference in both molecules.','Rotation about that axis can preserve the axial sigma overlap.','A sigma connection can persist during torsion.'),move('Identify the extra ethene pi alignment requirement.','Its parallel residual p functions overlap laterally; relative group twist changes that alignment.','Ethene twist alters pi overlap; ethane has no corresponding C-C pi component.'),move('Separate rigid rotation from relative torsion.','Only relative orientation about the bond changes the participating p relation.','Rotating the whole molecule does not reproduce twisting one group.'),move('Bound the energy inference.','Other interactions, including hyperconjugation, can change even when the central sigma connection remains.','No numerical barrier or exclusively steric total-energy law follows from the sketch.')],
 [move('Trace consecutive p-bearing carbon sites in butadiene.','An approximately planar conjugated chain supplies a p function at each of its four sp2 sites.','A four-site contiguous aligned p pathway.'),move('Trace the second molecule using the same local test.','Its intervening saturated CH2 uses localized sp3 accounting, with no ordinary residual p in this model.','The central spacer interrupts the contiguous pathway.'),move('Distinguish adjacency from spatial proximity.','Moving separated fragments near each other does not remove the saturated node from their bonding path.','The ordinary through-chain conjugation criterion remains unmet.'),move('State the model boundary explicitly.','Absence of the chosen contiguous p path does not exclude every possible quantum interaction.','No absolute zero-interaction claim; reassess if the spacer becomes p-bearing and suitably aligned.')],
 [move('Test one-label-per-molecule on propyne.','Its carbon local inventories differ: four, two, two directions.','sp3, sp, sp; a single whole-molecule label fails.'),move('Test the procedure on allene.','The terminal and central inventories are three, two, three directions.','sp2, sp, sp2; two perpendicular central p directions must remain.'),move('Build the replacement atom-local procedure.','Count neighbours and lone pairs, conserve each local valence basis, then assign residual p roles.','A label and orbital ledger for each atom.'),move('Check neighbouring orientation and applicability.','Adjacent p functions must support the intended pi account; delocalisation or unusual occupancy can require a richer model.','A qualified local framework with explicit compatibility and stop-for-more-evidence checks.')],
],
'D4':[
 [move('Record the Lewis inventory and the supplied donation condition separately.','N has three bonds plus a lone pair, but the task also supplies approximately planar donation into an adjacent carbonyl pi system.','A four-entry Lewis ledger does not settle the electronic model.'),move('Choose a basis that represents both jobs.','Three in-plane sp2-like sigma directions can coexist with an aligned p-like lone-pair donor under the supplied model.','A planar sigma framework plus a p-like donor connected to the carbonyl pi space.'),move('Explain why automatic sp3 assignment is inadequate.','A localized tetrahedral rule omits the stated delocalisation and alignment conditions.','The local count is a useful ledger, not an overriding proof of the basis.'),move('Bound and counterfactually test the description.','Twisting or interrupting the donor-acceptor path changes the applicability; geometry alone does not uniquely measure hybrid coefficients.','An introductory sp2-like account is conditional, not unique observed orbital reality.')],
 [move('Inventory formamide electrons and connectivity.','CH3NO supplies 4+3+5+6 valence electrons and 6+3+7+8 total electrons.','18 valence; 24 total; H-C(=O)-NH2 connectivity fixed.'),move('Construct the supplied aligned donor/carbonyl pi account.','The localized donor pair plus carbonyl pi pair gives four electrons in a three-centre qualitative pi space.','Aligned N p-like donor and C/O p directions; four model pi-space electrons.'),move('Rotate the N donor direction about C-N toward 90 degrees.','Relative torsion changes orientation against the fixed carbonyl reference; it does not change element counts.','Approximately orthogonal donor/acceptor directions with unchanged connectivity and electron ledger.'),move('Check what the two sketches can establish.','Orientation distinguishes alignment, while donation strength needs an experiment or specified calculation.','Both drawings retain 18 valence/24 total electrons; no measured donation strength is claimed.')],
 [move('Use the supplied model result as a conditional premise.','The benchmark specifies reduced alignment and delocalisation contribution toward 90-degree twist.','Connectivity fixed; relevant orbital directions rotate relative to each other.'),move('Connect torsion to the overlap mechanism.','Parallel p-like donor/acceptor directions support lateral interaction; orthogonal directions reduce that particular alignment.','Reduced alignment explains the stated qualitative contribution change.'),move('Test the hybrid-label-only explanation.','A label does not encode the adjacent acceptor or their relative orientation.','Renaming hybridisation alone is insufficient; the alignment pathway supplies the mechanism.'),move('Separate model contribution from measured total energy.','Other energy terms and relaxation can also vary under torsion.','No unique physical basis, numerical barrier or full total-energy law follows from this qualitative account.')],
 [move('Apply the same N Lewis ledger at both sites.','Both neutral N sites have three sigma bonds and one lone pair.','Local count alone does not distinguish A from B.'),move('Trace donor-to-carbonyl adjacency and p availability.','A has direct N-C(=O) adjacency; B contains the supplied saturated CH2 interruption.','A supports the stated contiguous donor/acceptor path; B lacks that ordinary path.'),move('Test alignment and validity before applying a label.','Donation requires suitable orbital orientation as well as adjacency; spatial proximity does not create conjugation.','Use conditional delocalised accounting at A and localized amine accounting at B within the given model.'),move('Construct a structural counterfactual.','Replacing the saturated interruption with a p-bearing aligned bridge changes the path test.','Reassess the model; absence of this ordinary path is not an absolute zero-interaction theorem.')],
 [move('Compare the supplied angles with their shared introductory label.','CH4, NH3 and H2O use sp3-like descriptions but have different lone-pair counts and nuclear shapes.','109.5, about 107 and about 104.5 degrees are compatible with the supplied shared label.'),move('Reject the unique-angle implication.','A single model label does not fix all interactions that affect geometry.','Angle deviations alone do not falsify every sp3-like description.'),move('Include the amide boundary in the replacement rule.','An aligned adjacent acceptor and delocalisation can make automatic localized four-domain classification inadequate.','Local counts guide a bounded starting model; lone pairs, alignment and delocalisation require additional checks.'),move('Specify evidence needed for stronger physical claims.','Nuclear geometry alone does not uniquely recover wavefunctions or a hybrid decomposition.','Use defined spectroscopic/electronic-structure evidence and model assumptions; retain alternative compatible descriptions.')],
 [move('Recall the local rule with its scope.','Four domains classify ordinary localized introductory centres; recalling it does not show that locality holds.','Starting ledger: three N bonds plus one lone pair.'),move('Inspect the supplied adjacency condition.','A has a carbonyl acceptor directly adjacent; B has a saturated interruption in the ordinary p path.','A needs a delocalisation/alignment test; B supports the local starting model here.'),move('Identify evidence that defeats automatic application.','Suitable donor/acceptor alignment, donation evidence or unusual occupancy add jobs the bond/pair total does not resolve.','Do not infer adequacy from the number four alone.'),move('Separate known conditions from unknown quantities.','Neither exact donor strength nor unique hybrid coefficients are supplied by this ledger.','Apply a conditional classification or request the missing electronic evidence.')],
 [move('Read the supplied radical geometry and occupancy.','The benchmark specifies three planar C-H sigma directions and a perpendicular singly occupied p-like orbital.','A three-direction sigma frame plus one unpaired electron.'),move('Allocate the carbon valence basis.','An sp2-like sigma allocation uses three functions and leaves one p-like function perpendicular.','Three hybrids plus one residual p-like function; four functions total.'),move('Place the supplied electron in the residual orbital.','CH3 radical has 4+3=7 valence electrons; three sigma pairs use six.','Residual p-like SOMO contains one electron, not zero.'),move('Compare with a six-electron CH3+ model inventory.','Removing one electron changes residual occupancy while the three-bond count can remain.','Three sigma bonds alone do not determine whether residual p is empty; the given radical model is not a universal claim.')],
 [move('State competing predictions before proposing observations.','The proposed localized pyramidal and donation-compatible planar accounts differ in nuclear arrangement and possible electronic consequences.','Compare N geometry, relevant bond metrics and condition-specific electronic or dynamic signals.'),move('Propose controlled geometry and bond measurements.','Defined species, phase and conditions allow predictions to be compared with uncertainty and alternative causes.','Near-planarity can challenge a strictly pyramidal description; bond metrics add constraints.'),move('Add an independent electronic or torsional test.','A specified spectrum or calculation/experiment can test donation-related or rotation-related predictions under stated assumptions.','A second channel of evidence can discriminate accounts more strongly than geometry alone.'),move('Limit the warranted inference.','Compatible geometry can arise under multiple electronic descriptions; strength and barrier require quantitative evidence.','No unique hybrid coefficients, donation magnitude or rotational barrier is measured by a qualitative planar sketch.')],
 [move('Evaluate the supplied overlap factor at the three angles.','The stated model is cos(theta); cos(0)=1, cos(60)=1/2 and cos(90)=0.','Factors: 1, 1/2, 0.'),move('Identify the missing link from overlap to total energy.','An overlap factor is not a Hamiltonian and supplies no full energy budget.','The proposed total-energy conclusion is not warranted.'),move('Construct an explicit counterexample to uniqueness.','At fixed theta=60 an independently specified energy contribution can vary while the overlap factor stays 1/2.','Same overlap, different total energy; proportionality is not implied.'),move('Bound even alternative energy approximations.','A squared-interaction estimate needs stated weak-coupling assumptions; a degenerate two-level coupling can instead yield epsilon plus/minus absolute t.','No universal cosine or cosine-squared total-energy law; both functions are even, so parity does not select one.')],
 [move('Audit each case for the explanatory job omitted by the slogan.','NH3 needs lone-pair versus nuclear-shape distinction; allene needs residual-p orientation; formamide needs donation conditions; the separated amine needs a pathway test.','A label alone cannot supply all four explanations.'),move('Retain local counting as a starting ledger.','Atom-local sigma directions and central pairs give useful introductory information when localized assumptions hold.','Count locally and conserve the valence basis.'),move('Add occupancy, adjacency and alignment branches.','A residual p function must have a specified occupancy and suitable neighbouring orbital path for the proposed interaction.','Check what orbitals do, rather than treating the hybrid label as their cause.'),move('Include a validity and evidence stopping rule.','Quantitative geometry/reactivity or competing compatible electronic accounts require evidence beyond the ledger.','Use a conditional framework and seek an explicit model or measurement when the simple rule is inadequate.')],
]}

def materialize(issue):
    band={34:'D2',33:'D2',36:'D3',35:'D3',38:'D4',37:'D4'}[issue]
    directory=ROOT/f'evidence/blueprint-cycles/ISS{issue}/inputs'
    b=json.loads((directory/'owner.bank.json').read_text());p=json.loads((directory/'package.v1.json').read_text())
    baseline=json.loads(subprocess.check_output(['git','show','1facd846101c74a69389f9cc6df5b7dbfebd5bea:'+str((directory/'owner.bank.json').relative_to(ROOT)).replace('\\','/')],cwd=ROOT))
    baseline_qs={q['id']:q for q in baseline['questions']}
    for n,q in enumerate(b['questions']):
        route=[]
        old_ids=[r['id'] for r in baseline_qs[q['id']]['answer']['reasoning_route']]
        for i,(action,why,output) in enumerate(ROUTES[band][n],1):
            route.append({'id':old_ids[i-1] if i<=len(old_ids) else q['id']+f'-MOVE-{i}','kind':('DECIDE','CONNECT','TRANSFORM','VERIFY')[i-1], 'action':action,'why_valid':why,'inputs':[q['stem'] if i==1 else route[-1]['output']], 'output':output})
        r=q['extensions']['grade9v3:learning_repair']
        q['answer'].update(reasoning_route=route,crux_move_ref=route[1]['id'],summary=r['rule'],check=r['check'])
        r['crux_move_ref']=route[1]['id']
    qs={q['id']:q for q in b['questions']}
    for m in p['microtopics']:
        for u in m['construction_units']:
            target=qs[u['bank_anchor_ref']];rows=target['answer']['reasoning_route']
            selected=[s for s in m['teaching_path'] if s['id'] in u['step_refs']]
            for i,s in enumerate(selected):
                row=rows[min(i,len(rows)-1)];s.update(action=row['action'],why_valid=row['why_valid'],output=row['output'])
            r=target['extensions']['grade9v3:learning_repair']
            anchor=m['extensions'].get('grade9v3:lesson_anchors',{}).get(u['id'])
            if anchor:
                anchor['target_crux_move_ref']=qs[anchor['target_question_ref']]['answer']['crux_move_ref']
                answer=r['pattern'].split(' Repeated')[0].split(' A repeated')[0].split(' Recurrent')[0].split(' Persistent')[0]
                anchor['answer'].update(summary=answer,reasoning=[r['connect'],answer,r['rule']],check=r['check'])
            u['crux_step_ref']=u['step_refs'][min(1,len(u['step_refs'])-1)]
        m['extensions']['grade9v3:question_repairs']=[q['extensions']['grade9v3:learning_repair'] for q in b['questions'] if q['extensions']['grade9v3:learning_repair']['microtopic_ref']==m['id']]
    write(directory/'owner.bank.json',b);write(directory/'package.v1.json',p)
    print(f'ISS{issue}: ten concrete {band} routes; source payload unchanged.')

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('issue',type=int,choices=[34,33,36,35,38,37]);materialize(a.parse_args().issue)
