"""Author separately labelled calibration specimens for the eight missing cells.

These are original practice, not additional owner inputs or authenticated exam
questions. Difficulty/classification estimates require independent calibration.
"""
import copy, hashlib, json
import os
from pathlib import Path
from Shared.tools import product_manifest
from academic_bridge_svg import matrix_framework

ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/os.environ.get('G9_REVIEW_DIR','evidence/blueprint-cycles/closure-20261005')/'matrix'
KEYS=['concept_model_selection','representation_translation','reasoning_chain_length','algebra_computational_load','trap_exception_sensitivity']

# Each tuple includes the actual decisive act, five-component estimate, protected
# support, solution and changed-case diagnostic. Bands are checked against the
# canonical ranges, rather than assigning a band from a desired label alone.
CASES=[
 dict(demand='RETRIEVE',band='D2',vector=[0,1,1,1,1],title='Classify after putting the equation in standard form',
  stem='Over the rationals, classify 3x − 4 = 1 − 2x as having no solution, one solution, or every rational as a solution. Use the criterion Ax = B: A nonzero gives one rational solution, A = B = 0 gives every rational, and A = 0 with B nonzero gives none. Do not report the value of x.',
  basis='The requested act is category selection. Translating two expressions into Ax=B, keeping signs, and connecting the reduced coefficients to the category require connected reasoning; finding the numerical root is not requested.',
  secondary=['APPLY','REPRESENT'],hints=['Keep the question about the size of the solution set, rather than a numerical root.','Collect the two variable terms and the constants on separate sides; preserve each sign.','Identify A and B in your reduced line and compare with the supplied criteria; choose the category yourself.'],
  moves=[('Collect the variable terms.','Adding 2x to both complete sides preserves equality.','5x − 4 = 1'),('Remove the constant.','Adding 4 to both sides is reversible.','5x = 5'),('Select the category.','The coefficient 5 is nonzero, so exactly one rational can satisfy the equation.','One solution.'),('Challenge an all-solutions claim.','One counterexample suffices to refute that every rational works.','x=0 gives −4 and 1, which differ.')],
  answer='One solution.',check='At x=0 the two sides differ, so the category is not every rational. The nonzero coefficient rules out none.',
  wrong='Any linear-looking equation has every rational as a solution.',probe='Classify 4x+1=4x+1 and 4x+1=4x+2. Do not solve by dividing by the cancelled coefficient.',repair='The first has every rational; the second has none. The reduced constant comparison matters when the coefficient is zero.',
  diagram=['Requested output: category of solution set','3x − 4    =    1 − 2x','No solution | One solution | Every rational'],
  transfer='Classify 7x+2=7x+3. Expected: no solution, because it reduces to 2=3.'),
 dict(demand='RETRIEVE',band='D3',vector=[0,1,2,1,2],title='Classify linked parameter exceptions',
  stem='Let k be rational and x rational. For each k, classify each of these equations as having none, one, or every rational solution: E1: 2(x−3)=2x+k; E2: (k−2)x=4−2k. Use the Ax=B criteria; a numerical solution is not requested.',
  basis='Category reconstruction stays primary. Bracket reduction and the parameter-dependent coefficient must be coordinated; k=−6 and k=2 control different exceptions. Representation 1, chain 2, algebra 1 and exception sensitivity 2 total 6.',
  secondary=['APPLY','SYNTHESIZE','JUSTIFY'],hints=['Keep the two equations separate; k is a fixed parameter when you classify solutions in x.','Put each equation in Ax=B form, without dividing by any expression that could vanish.','Partition k only where your reduced coefficient or constant changes the classification. Decide the categories yourself.'],
  moves=[('Expand E1 and cancel 2x.','Distribution and subtracting the same term from both sides preserve the solution set.','E1 becomes −6=k.'),('Classify E1.','The reduced statement has no x, so it holds for all x or for none.','Every rational if k=−6; none otherwise.'),('Factor the E2 constant.','4−2k=−2(k−2).','(k−2)x=−2(k−2).'),('Separate k=2 before division.','At k=2 both sides vanish; division by k−2 would lose this case.','E2 has every rational if k=2.'),('Classify the remaining k.','A nonzero rational coefficient has a unique rational quotient.','E2 has one rational solution for k≠2.'),('Cross-check the exceptional parameters.','Each category must be evaluated in the original pair.','At k=−6: E1 every, E2 one. At k=2: E1 none, E2 every.')],
  answer='E1: every rational at k=−6, none otherwise. E2: every rational at k=2, one otherwise.',check='Substitute k=−6 and k=2 in both originals. Neither equation has a hidden division step at its exceptional parameter.',
  wrong='Cancelling a parameter factor is valid even where the factor is zero.',probe='Classify (t−3)y=2(t−3) at t=3 and t=4, keeping the exceptional case.',repair='At t=3 every rational works; at t=4 exactly one works. Split a zero divisor before cancelling.',
  diagram=['k is fixed; x ranges over rationals','E1: 2(x−3) = 2x+k','E2: (k−2)x = 4−2k'],
  transfer='Classify (t+1)y=3(t+1). Expected: every rational at t=−1; one otherwise.'),
 dict(demand='RETRIEVE',band='D4',vector=[2,2,2,2,2],title='Classify with a coupled domain boundary',
  stem='Extension beyond routine linear equations. k is real, x must be rational. Classify the simultaneous system by k as INVALID PARAMETER, NO RATIONAL SOLUTION, ONE RATIONAL SOLUTION, or EVERY RATIONAL SOLUTION: (k−1)(k−2)x=k−1 and (x+1)/(x−1)=k/(k−2). An equation with a zero denominator is invalid; a solution must satisfy both original equations and x≠1. Report categories and the parameter cases, not a general numerical solution method.',
  basis='The final act is classification against explicit category boundaries. Real parameter versus rational unknown, a coupled rational expression, zero-factor exceptions, and compatibility of two independently reduced constraints require all five components at 2 (10). This advanced category specimen has secondary synthesis and justification and is provisional; it is not routine recall relabelled D4.',
  secondary=['SYNTHESIZE','JUSTIFY','APPLY','MODEL'],hints=['Distinguish an undefined equation from an equation that is defined but has no rational solution.','The parameter and unknown have different declared domains. Keep both original equations as requirements.','Keep excluded denominators and zero factors explicit before any cancellation. The compatibility and classification decisions remain yours.'],
  moves=[('Exclude the parameter making the second equation undefined.','Its right denominator k−2 must be nonzero.','k=2 is INVALID PARAMETER.'),('Isolate the zero-factor case k=1.','The first equation then reads 0=0, while the second remains defined.','The second becomes (x+1)/(x−1)=−1, giving x=0; it is rational and allowed.'),('Reduce the first equation for k outside {1,2}.','Only in this branch is cancellation of k−1 followed by division by k−2 valid.','x=1/(k−2).'),('Reduce the second equation with both denominator conditions retained.','Cross-multiplication is reversible when x≠1 and k≠2.','(k−2)(x+1)=k(x−1), hence x=k−1.'),('Require the two candidates to coincide.','Both original equations must hold for the same x.','(k−1)(k−2)=1, hence k²−3k+1=0.'),('Use the rational-domain restriction.','The only compatibility parameters (3±√5)/2 are irrational; x=k−1 is then irrational and excluded.','No rational solution for every k outside {1,2}.'),('Verify the exceptional allowed branch in the originals.','A reduced-line result is insufficient when divisions were used in other branches.','k=1,x=0 gives 0=0 and 1/(−1)=1/(−1). ONE at k=1; INVALID at k=2; NONE otherwise; never EVERY.')],
  answer='ONE RATIONAL SOLUTION at k=1; INVALID PARAMETER at k=2; NO RATIONAL SOLUTION for every other real k; never EVERY.',check='At k=1, x=0 satisfies both originals. At k=2 a denominator is zero. At the two real compatibility roots, x is irrational, so a real solution does not meet the rational-domain request.',
  wrong='A real solution found after cancelling is automatically an allowed rational solution.',probe='Let y be rational and a real. Classify (a−2)y=1 at a=2, a=3 and a=2+√2. Keep undefined operations separate from empty solution sets.',repair='At a=2 the equation is defined but inconsistent (no solution); at a=3 exactly one rational works; at a=2+√2 the sole real candidate 1/√2 is irrational, so no rational works. Domain checks come after valid branch reduction.',
  diagram=['k real; x rational; both equations required','(k−1)(k−2)x = k−1','(x+1)/(x−1) = k/(k−2); denominators nonzero'],
  transfer='Change the unknown domain to real. Expected: one solution also at k=(3±√5)/2; k=1 remains one, k=2 invalid, all other k none.'),
 dict(demand='APPLY',band='D3',vector=[0,2,2,1,1],title='Execute an inverse chain across a table and a process graph',
  stem='A measuring program uses numerical readings in centimetres: X → A=(X−1)/2 → B=3A+4 → C=(B+2)/5. The observation table gives C=22 millimetres. The inverse procedure is prescribed: convert the observation to centimetres, undo the C operation, then B, then A. Execute it to recover X and verify every forward stage. Treat the displayed readings as exact.',
  basis='The governing procedure and inverse order are supplied, so execution is primary. The millimetre table must become a centimetre reading, the graph aliases must be tracked backward, and three dependent operations checked; representation 2, chain 2, algebra 1, unit/undo sensitivity 1 total 6.',
  secondary=['REPRESENT','SYNTHESIZE'],hints=['Keep the observation unit separate from the program unit.','Map each graph letter to its defining operation before substituting a number.','Start with the prescribed unit conversion, then apply the inverse steps in the given order. Leave the arithmetic and final reading to your attempt.'],
  moves=[('Convert the exact observation.','Ten millimetres are one centimetre.','C=22/10=11/5 centimetres.'),('Undo C=(B+2)/5.','Multiplication by nonzero 5 and subtraction of 2 reverse this stage.','B=5C−2=9.'),('Undo B=3A+4.','Subtract 4, then divide by nonzero 3.','A=(9−4)/3=5/3.'),('Undo A=(X−1)/2.','Multiply by nonzero 2, then add 1.','X=2(5/3)+1=13/3 centimetres.'),('Run the entire forward chain.','A correct recovered input must reproduce the original observation after every named operation.','13/3 → 5/3 → 9 → 11/5 centimetres = 22 millimetres.')],
  answer='X=13/3 centimetres.',check='The forward chain gives A=5/3, B=9, C=11/5 cm =22 mm, so neither a unit mistake nor a reversed-step mistake survives the check.',
  wrong='The table number can be substituted directly although the program uses a different unit.',probe='Run the same inverse program with C=20 millimetres, and separately with C=2 centimetres. Should X differ?',repair='These are the same observation. Both give B=8, A=4/3 and X=11/3 cm. Different results reveal a unit mapping error.',
  diagram=['Observation table: C = 22 mm; program uses cm','X → subtract 1, divide 2 → A','A → multiply 3, add 4 → B → add 2, divide 5 → C'],
  transfer='Use C=20 mm. Expected X=11/3 cm; the forward chain gives 2 cm.'),
 dict(demand='MODEL',band='D1',vector=[1,0,0,0,1],title='Choose the governing equation from its conditions',
  stem='A linear calibration is stated as Ax=B with rational A and B, and A is known to be nonzero. Choose the governing rule for recovering x: R1, x=B/A; R2, infer every rational is a solution from 0=0. Only choose the applicable rule; do not compute a value.',
  basis='One explicit model/strategy choice and one zero-coefficient boundary trap total 2. The output is the governing rule, not a recalled category or computed root.',secondary=['RETRIEVE'],
  hints=['Identify the condition on the coefficient before choosing a rule.','Compare each candidate rule with its coefficient assumption.','Choose the rule whose assumption matches the stated coefficient; the winning rule remains yours.'],
  moves=[('Read the coefficient condition.','The problem explicitly excludes A=0.','A is nonzero.'),('Select R1.','Division by the fixed nonzero rational A is defined and reversible.','Use x=B/A.'),('Check the alternative boundary.','The all-solutions rule needs A=B=0 and therefore conflicts with the given A≠0.','R2 does not apply.')],
  answer='R1, x=B/A.',check='The boundary A=B=0 would admit R2, showing why the stated nonzero condition determines this choice.',
  wrong='Use the all-solutions rule for every linear calibration.',probe='Choose the rule when A=0,B=0, and when A=0,B=1.',repair='The first admits every rational, the second none. A rule is selected by both coefficients, not the word linear.',diagram=['Given: Ax = B; A ≠ 0','Candidate R1: divide by A','Candidate R2: zero-coefficient identity'],transfer='For A=0,B=1, neither division by A nor the all-solutions rule applies; use inconsistency 0=1.'),
 dict(demand='REPRESENT',band='D1',vector=[0,1,0,0,0],title='Translate an ordered pair without changing meaning',
  stem='The ordered-pair table has columns x and y and one row x=2, y=3. Write that row as a point in Cartesian ordered-pair notation. The coordinate convention is horizontal x first and vertical y second; no equation solving is requested.',
  basis='One direct representation translation preserves the two coordinate roles; no model choice, chain or algebra is needed (1).',secondary=[],
  hints=['Keep each value attached to its column heading.','The first coordinate names the horizontal axis.','Use the supplied order while filling the pair yourself.'],moves=[('Map the table headings to coordinate slots.','The convention gives the first slot to x and the second to y.','Slots are (x,y).'),('Insert the two labelled values.','The row assigns x=2 and y=3.','(2,3).'),('Check a swapped pair.','Its first coordinate would claim x=3, contrary to the row.','(3,2) represents a different point.')],answer='(2,3).',check='Reading the pair back gives x=2,y=3, preserving both table headings.',wrong='An ordered pair may swap its two coordinates without changing the point.',probe='Translate rows x=4,y=1 and x=1,y=4. Are their points identical?',repair='They give (4,1) and (1,4), distinct points. Coordinate roles are part of the meaning.',diagram=['Table heading: x | y','Row:            2 | 3','Coordinate template: (horizontal, vertical)'],transfer='Translate x=−1,y=5. Expected (−1,5).'),
 dict(demand='SYNTHESIZE',band='D1',vector=[0,0,1,0,1],title='Order two dependent inverse steps',
  stem='A starting number is first increased by 3 and then doubled, producing 14. You know the inverse components: subtract 3, and halve. Coordinate them into the correct reverse order. State which component must come first and why; do not calculate the starting number.',
  basis='The decisive act is ordering two dependent known components. One short dependency and one order trap total 2; neither model selection nor numerical execution is asked.',secondary=['APPLY'],
  hints=['The final output comes from the last forward operation.','Each inverse must receive the output of the operation it undoes.','Trace the dependency backward and choose the first inverse yourself.'],moves=[('Read the forward dependency.','The doubled quantity already includes the added 3.','Start → add 3 → double → output.'),('Reverse the outer operation first.','Halving recovers the quantity before doubling, which still contains the added 3.','Halve first, then subtract 3.'),('Check the competing order on a changed start.','An independent forward/reverse check tests the dependency rather than memorising a rule.','Start 2 gives output 10; halve then subtract gives 2, subtract then halve gives 3.5.')],answer='Halve first, then subtract 3; undo the last operation before its input operation.',check='For a changed start 2, the forward output is 10; the selected inverse returns 2 while the competing order returns 3.5.',wrong='Inverse components can be performed in any order.',probe='For forward double then add 3, which inverse comes first? Compare with forward add 3 then double.',repair='The first needs subtract 3 then halve; the second halve then subtract 3. The component list is unchanged, but the dependency changes.',diagram=['Start → add 3 → double → 14','Inverse components: halve | subtract 3','Required: dependency-respecting order'],transfer='Change the forward order to double then add 3. Expected first inverse: subtract 3.'),
 dict(demand='JUSTIFY',band='D1',vector=[0,0,1,0,1],title='Give the warrant for a reversible division',
  stem='Over the reals, an author concludes x=4 from 2x=8 by dividing both sides by 2. Supply one warrant explaining why the conclusion follows and why the same justification would fail for division by zero. No further equation solving is requested.',
  basis='One explicit nonzero-divisor warrant establishes the conclusion, with one boundary trap (2). The answer is a validity argument, not the numerical calculation already supplied.',secondary=['RETRIEVE'],
  hints=['The result is already stated; the question asks what licenses the step.','Think about whether the operation is defined and can be undone.','State the relevant property of the divisor and connect it to preserved equality yourself.'],moves=[('State the divisor property.','The given divisor 2 is nonzero.','Division by 2 is defined.'),('Connect the operation to its inverse.','Multiplying both sides back by 2 restores the same equality.','The step is reversible and preserves the solution set, establishing x=4.'),('Challenge the zero-divisor boundary.','Division by zero is undefined, so it has no reversible operation of this kind.','The warrant cannot license division by zero.')],answer='Because 2 is nonzero, dividing both sides by 2 is defined and reversible, preserving equality and the solution set. Division by zero is undefined.',check='Multiplication by 2 takes x=4 back to 2x=8. The zero-divisor case lacks this reversible division.',wrong='Doing any identical operation on both sides automatically preserves the solution set.',probe='From x=1 multiply both sides by zero. Does the resulting equation have exactly the original solution?',repair='It becomes 0=0 and admits every real, so the non-reversible step enlarged the solution set. Identical operations need the relevant reversibility condition.',diagram=['Premise: 2x = 8','Claim: x = 4','Requested: a warrant for the division step'],transfer='Justify dividing 3x=9 by 3. Expected: nonzero, defined, reversible; multiplying back verifies the argument.')
]

def save(path,obj):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')

def main():
    # Independent review rejected RETRIEVE ownership: deriving compatibility
    # from simultaneous constraints is synthesis. Do not force the missing cell.
    disputed=next(c for c in CASES if c['demand']=='RETRIEVE' and c['band']=='D4')
    disputed.update(demand='SYNTHESIZE',secondary=['JUSTIFY','APPLY','MODEL','RETRIEVE'],
        basis='Compatibility coordinates two independently reduced constraints, denominator restrictions and a rational-domain test. Independent review assigns SYNTHESIZE primary at D4; this does not fill RETRIEVE D4.')
    original=json.loads((ROOT/'Mathematics/library/linear-equations.v1.json').read_text(encoding='utf-8'))
    p=copy.deepcopy(original)
    p.update(package_id='LIB-ISS29-MATRIX-CALIBRATION',title='Eight supplementary demand/band calibration tasks',
       scope_summary='Original author-created review specimens for missing QRT cells. D4 parameter/domain classification is an explicitly advanced extension, not a routine Grade 9 claim.',status='CANDIDATE')
    for collection in ('capabilities','microtopics','relations','representations','question_families','questions','data','teaching_routes','practice_profiles','evidence','known_issues','application_contexts'):p[collection]=[]
    resource=copy.deepcopy(original['resources'][0]);resource.update(id='SRC-ISS29-SUPPLEMENT',title='Original matrix calibration practice',locator='https://github.com/reallaksh19/Grade9v3.5/issues/29',source_refs=[],evidence_refs=[],extensions={})
    p['resources']=[resource]
    bucket=copy.deepcopy(original['buckets'][0]);bucket.update(id='BUCKET-ISS29-SUPPLEMENT',title='Algebraic decisions and domain boundaries',topic='Algebraic decisions and domain boundaries',source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],extensions={})
    p['buckets']=[bucket];ledger=[]
    templates=json.loads((ROOT/'Shared/quality/question-demand-templates.v1.json').read_text(encoding='utf-8'))
    template_rows=templates['templates']
    for n,c in enumerate(CASES,1):
        qid=f'CAL-ISS29-{c["demand"]}-{c["band"]}';capid='CAP-'+qid;mid='MIC-'+qid;famid='FAM-'+qid;repid='REP-'+qid
        cap=copy.deepcopy(original['capabilities'][0]);cap.update(id=capid,source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],extensions={},action=c['title'],success_criterion=c['answer'],prerequisite_refs=[]);p['capabilities'].append(cap)
        m=copy.deepcopy(original['microtopics'][1]);m.update(id=mid,source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],extensions={},title=c['title'],bucket_id=bucket['id'],primary_capability_ref=capid,prerequisite_refs=[],relation_refs=[],representation_refs=[repid],question_family_refs=[famid]);p['microtopics'].append(m)
        family=copy.deepcopy(original['question_families'][0]);family.update(id=famid,source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],extensions={},title=c['title'],capability_refs=[capid],item_refs=[qid]);p['question_families'].append(family)
        q=copy.deepcopy(original['questions'][0]);q.update(id=qid,status='CANDIDATE',source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],origin='AUTHORED',origin_ref='SRC-ISS29-SUPPLEMENT',original_identifier=qid,stem=c['stem'],conditions=['Original calibration practice; independent educational review pending.']+(['Advanced parameter/domain extension; not an ordinary Grade 9 retrieval question.'] if c['band']=='D4' else []),figure_refs=[repid],primary_capability_ref=capid,secondary_capability_refs=[],family_ref=famid,exposure=[{'core':'CORE2A','role':'PRACTICE','artifact_ref':None}],failure_signal=c['wrong'],family_exposure={'family_ref':famid,'closure':c['transfer']})
        q.pop('verification',None)
        score=sum(c['vector']);ranges=json.loads((ROOT/'Shared/vocabularies/learner-question-metadata.v1.json').read_text())['question_difficulty_score_ranges'][c['band']]
        assert ranges['min']<=score<=ranges['max']
        q['difficulty']={'band':c['band'],'score':score,'components':dict(zip(KEYS,c['vector'])),'basis':c['basis']}
        q['extensions']={'grade9v3:analysis':{'cognitive_demand':{'primary':c['demand'],'secondary':c['secondary']},'stable_crux_move':c['title']},'grade9v3:qrt_template':{'template_id':f'QRT-{c["demand"]}-{c["band"]}','status':'AUTHOR_ESTIMATE_REQUIRES_INDEPENDENT_CALIBRATION'},'grade9v3:authorship':{'kind':'AI_AUTHORED_CALIBRATION','owner_supplied':False,'personally_owner_authored':False}}
        route=[{'id':qid+f'-MOVE-{i}','kind':'VERIFY' if i==len(c['moves']) else 'TRANSFORM','action':a,'why_valid':w,'inputs':[c['stem']] if i==1 else [c['moves'][i-2][2]],'output':o} for i,(a,w,o) in enumerate(c['moves'],1)]
        q['answer']={'kind':'MODEL_RESPONSE','summary':c['answer'],'reasoning':[a+' '+w+' '+o for a,w,o in c['moves']],'reasoning_route':route,'crux_move_ref':route[-2]['id'],'check':c['check'],'acceptable_alternatives':[],'subpart_answers':[],'verification_status':'CHECKED_BY_AUTHOR'}
        q['hints']=[{'text':t,'reveals':'CONCEPT'} for t in c['hints']]
        q['hint_ladder']=[{'order':i,'purpose':purpose,'from':f'hints[{i-1}]','provenance':'AUTHORED_HINT'} for i,purpose in enumerate(['ORIENT','REPRESENT','FIRST_RELATION'],1)]
        q['independent_check']={'statement':c['check'],'check_type':'SUBSTITUTION_BACK_CHECK'}
        q['repair_ref']=route[-2]['id']
        m['entry_assumptions']=['Use the exact declared domains and the stated category/operation conventions.']
        m['inferential_jump']=c['repair'];m.pop('elicitation',None)
        m['teaching_path']=[{'id':row['id'],'action':row['action'],'why_valid':row['why_valid'],'inputs':row['inputs'],'output':row['output'],'role':'VERIFY' if row['kind']=='VERIFY' else 'TRANSFORM'} for row in route]
        unit=copy.deepcopy(original['microtopics'][1]['construction_units'][0])
        unit.update(id='CU-'+qid,decision=c['title'],step_refs=[r['id'] for r in route],representation_ref=repid,reveal_stage_refs=[qid+'-VIS-1',qid+'-VIS-2'],worked_anchor_ref=qid,misconception_indexes=[0],independent_checks=[{'statement':c['check'],'check_type':'SUBSTITUTION_BACK_CHECK'}])
        m['construction_units']=[unit];m['misconceptions']=[{'wrong_idea':c['wrong'],'diagnostic_prompt':c['probe'],'repair':c['repair']}]
        m['exit_task']={'oracle':{'held_by':'ISS-REVIEW-'+qid},'prompt':c['probe'],'source_ref':'SRC-ISS29-SUPPLEMENT','answer':{'kind':'MODEL_RESPONSE','summary':c['repair'],'reasoning':[c['repair']],'check':c['transfer'],'acceptable_alternatives':[],'subpart_answers':[],'verification_status':'CHECKED_BY_AUTHOR'}}
        p['known_issues'].append({'id':'ISS-REVIEW-'+qid,'affected_refs':[mid,qid],'classification':'SCIENTIFIC_REVIEW_REQUIRED','description':'Author solution and classification are review candidates, not an independent oracle.','next_action':'Review the exact specimen, domain branches, five components and support before acceptance.'})
        m['compact_anchor']={'prompt':c['stem'],'result':c['answer']}
        m['extensions']={'grade9v3:component_waivers':{'EQUATIONS':'This calibration unit uses the explicit equation/encoding in its stem; no additional general relation is authored.'}}
        family['solution_structure']=[row['action'] for row in route];family['common_wrong_routes']=[c['wrong']]
        family['safe_variations']=['Preserve the declared domains and nonzero conditions; separately solve every changed case.']
        family['transfer_boundaries']=['A changed criterion or domain requires fresh classification; this specimen grants no universal acceptance.']
        stages=[{'id':qid+'-VIS-1','label':'Givens and requested output','purpose':'Separate the declared givens and representation roles from the protected decision.','visible_elements':['givens']},{'id':qid+'-VIS-2','label':'Construction framework','purpose':'Expose the task-specific correspondence and unfilled decision entries.','visible_elements':['givens','domain reminder']}]
        svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 610" role="img" aria-label="'+c['title']+'" font-size="18"><title>'+c['title']+'</title><desc>Labelled givens and unfilled task-specific framework; no solution is shown in these stages.</desc>'
        import html
        svg+='<g data-g9-stage-id="'+stages[0]['id']+'"><rect x="12" y="12" width="670" height="130" fill="#eef4ff" stroke="#345"/>'
        for i,text in enumerate(c['diagram']):svg+=f'<text x="26" y="{43+i*36}" fill="#172d46">{html.escape(text)}</text>'
        svg+='</g><g data-g9-stage-id="'+stages[1]['id']+'">'+matrix_framework(c['demand'],c['band'])+'</g></svg>'
        asset=OUT/'assets'/f'{qid}.svg';asset.parent.mkdir(parents=True,exist_ok=True);asset.write_text(svg,encoding='utf-8',newline='\n')
        rep=copy.deepcopy(original['representations'][0]);rep.update(id=repid,source_refs=['SRC-ISS29-SUPPLEMENT'],evidence_refs=[],extensions={},purpose='Align declared givens, domains and requested output while preserving the decisive learner work.',relation_refs=[],rendered_asset_refs=[asset.relative_to(ROOT).as_posix()],reveal_stages=stages,required_elements=['givens','domain reminder'],read_order=['givens','domain reminder'],correspondence=[{'element':'givens','symbol':'declared quantities','in_words':c['stem']}],support_stage_map=[{'support_level':'low','visual_stage_ref':stages[0]['id']},{'support_level':'medium','visual_stage_ref':stages[1]['id']}]);p['representations'].append(rep)
        rep['extensions']={'grade9v3:stage_mode':'REPLACE'}
        q['representation_roles']={'initial_ref':repid,'safe_ref':None,'bound_ref':repid,'stage_refs':[s['id'] for s in stages]};p['questions'].append(q)
        template=next(t for t in template_rows if t['template_id']==f'QRT-{c["demand"]}-{c["band"]}')
        ledger.append({'id':qid,'primary':c['demand'],'secondary':c['secondary'],'band':c['band'],'qrt_id':template['template_id'],'qrt_sha256':hashlib.sha256(json.dumps(template,sort_keys=True).encode()).hexdigest(),'classification_rationale':c['basis'],'five_components':q['difficulty'],'protected_work':c['title'],'solution_moves':route,'check':c['check'],'diagnostic':{'wrong_idea':c['wrong'],'probe':c['probe'],'repair':c['repair'],'interpretation':'A repeated wrong rule across changed cases is evidence to investigate a held idea; one response is not a mastery verdict.'},'facets':{'H1':c['hints'][0],'H2':c['hints'][1],'H3':c['hints'][2],'S1':'Givens and requested output, no answer.','S2':'Boundary reminder retains domains; no computed or selected result.','S3':'No third visual is needed: additional staging would repeat the same constraints.','P1':'Hints and both visual stages preserve the requested decision.','P2':'The repair link lands on CU- plus the exact specimen ID, whose teaching path includes the decisive warranted move. Familiar practice follows the worked exposure; the changed diagnostic/exit is a separate case.','P3':c['check'],'M1':c['wrong'],'M2':c['probe'],'M3':c['repair']},'review_status':'AUTHOR_SELF_CHECK_REQUIRES_EXACT_RENDER_AND_INDEPENDENT_CALIBRATION'})
    save(OUT/'package.v1.json',p)
    manifest=product_manifest.derive((OUT/'package.v1.json').relative_to(ROOT).as_posix(),[],'PRODUCT-ISS29-MATRIX-CALIBRATION','index.html');manifest['output_roles']=['CORE1A','CORE2A'];manifest['selection']['core2a']=[q['id'] for q in p['questions']];save(OUT/'manifest.json',manifest)
    save(OUT/'calibration-ledger.json',{'schema':'issue29-matrix-calibration/v1','original_denominator':'80 owner instances / 40 distinct questions / 20 primary cells unchanged','supplement_count':8,'candidate_cell_union':27,'open_cells':['QRT-RETRIEVE-D4'],'claim':'Independent review reclassifies the advanced system as SYNTHESIZE D4. The candidate union is 27 cells; RETRIEVE D4 remains open. Reviewer recommendations are not owner acceptance.','specimens':ledger})
    for row in ledger:
        row['facets']['S2']='Task-specific unfilled construction framework in REPLACE mode; correspondence and boundary conditions are explicit while target decisions stay learner work.'
        row['facets']['S3']='Third stage waived: a completed decision belongs in protected solution/teaching; the two stages already expose givens and the useful unfilled framework.'
    save(OUT/'calibration-ledger.json',{'schema':'issue29-matrix-calibration/v1','original_denominator':'80 owner instances / 40 distinct questions / 20 primary cells unchanged','supplement_count':8,'candidate_cell_union':27,'open_cells':['QRT-RETRIEVE-D4'],'claim':'Independent review reclassifies the advanced system as SYNTHESIZE D4. The candidate union is 27 cells; RETRIEVE D4 remains open. Reviewer recommendations are not owner acceptance.','specimens':ledger})
    print('Eight authored specimens; independently recommended D4 synthesis; 27 candidate cells, RETRIEVE D4 open.')

if __name__=='__main__':main()
